### ISSUE TITLE
Support issue

### ISSUE THREAD

**Issue by minlearn** [openfaas/faasd#113]
this results two problem:

1) cant resolve faasd-provider to 10.62.0.1(openfaas0 interface),corrected /var/lib/faasd/docker-composer then reboot,works,

or it keep hinting "error finding function xxxx.: Get http://faasd-provider:8081/system/function/xxxx?namespace=: dial tcp: i/o timeout"

2)cant resovle app container(above xxxx) ip to 10.62.0.xx,disable system ipv6 by updating grub cmdline with "GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"" works,

ir it keep hinting "service xxxx not reached"

**Comment by alexellis** [comment]
Hi @minlearn thank you for your interest in faasd, please can you use the latest version which contains a feature to restart stopped containers like the one you mention above?

See: github.com/openfaas/faasd/releases

Alex

**Comment by minlearn** [comment]
> Hi @minlearn thank you for your interest in faasd, please can you use the latest version which contains a feature to restart stopped containers like the one you mention above?
> 
> See: github.com/openfaas/faasd/releases
> 
> Alex

0.9.2

**Comment by alexellis** [comment]
What does that comment mean?

<img width="1302" alt="Screenshot 2020-09-22 at 11 48 22" src="https://user-images.githubusercontent.com/6358735/93873460-a4b25c80-fcc9-11ea-887c-f4f774b2276d.png">

The version is 0.9.5

**Comment by minlearn** [comment]
just tried 0.9.5,the experiences are much better
