### ISSUE TITLE
undefined: log.Writer when compiling faasd

### ISSUE THREAD

**Issue by minlearn** [openfaas/faasd#117]
undefined: log.Writer when compiling faasd 0.9.5

git checkout 0.9.5
cd /src/github.com/openfaas/faasd,make local
the output:

```
CGO_ENABLED=0 GOOS=linux go build -o bin/faasd
# github.com/openfaas/faasd/pkg/logs
pkg/logs/requestor.go:104:51: cmd.String undefined (type *exec.Cmd has no field or method String)
pkg/logs/requestor.go:182:10: undefined: log.Writer
```

## Your Environment

* OS and architecture:ubuntu 18.04,go 1.12.4

* Versions: faasd 0.9.5

**Comment by alexellis** [comment]
Hi, thank you for your interest in faasd

I believe that your Go version is too old, please upgrade to 1.13 which we use and advise in the developer guide.
