### ISSUE TITLE
Is there support for the nats-connector in faasd?

### ISSUE THREAD

**Issue by hivethought** [openfaas/faasd#119]
Hi,

Sorry if this is not the right place to ask this, but I was wondering if the nats-connector is supported in faasd? I managed to install and use the nats-connector (https://github.com/openfaas-incubator/nats-connector) on a "regular" openfaas deployment (installed with arkade on top of kubernetes - w/ kind), and was wondering if there is any support for running the nats-connector with faasd? 

Thanks!

**Comment by alexellis** [comment]
This is likely to be possible soon. I believe that you can go ahead and run the connector with systemd or by adding it to your docker-compose.yaml

The missing piece for the connector-sdk is in #86 - but we have a PR up for that and it should be merged soon.

Short answer: coming very soon, long answer above.

Alex

**Comment by alexellis** [comment]
We have a release ready for testing -> https://github.com/openfaas/faasd/releases/tag/0.9.6

You can add the nats-connector to your docker-compose.yaml file, but at this stage, I would recommend you switch over to Slack for technical support.

**Comment by Waterdrips** [comment]
/close 

I *think* this is possible now

**Comment by alexellis** [comment]
Yes it is possible, an example was shared on openfaas Slack when I invited you on Oct 19th.

**Comment by wschenk** [comment]
I was looking for this example but slack i think doesn't keep the messages around.  I found a twitter post of a screenshot that I'm trying to work through, but i was wondering if it was documented anywhere.

**Comment by sidharthramesh** [comment]
I am looking for an example too. Is there anything available right now?

**Comment by sidharthramesh** [comment]
This project seems to use nats-connector with faasd: https://lucasroesler.com/posts/2021/event-driven-faasd-with-postgres/
Youtube link: https://www.youtube.com/watch?v=nGOZLOjg5Zs
