### ISSUE TITLE
Docker compose file not working

### ISSUE THREAD

**Issue by eloo** [openfaas/faasd#124]
Hello,
i'm currently trying to get faasd running on my local machine for testing. 
I'm trying to use the docker-compose file which is located in this repository but i'm having a bit trouble.

## Expected Behaviour
* faasd will be available by using the docker-compose file

## Current Behaviour
* nats container is having trouble to get started because of "command not found"

## Possible Solution
* not sure right now

## Steps to Reproduce (for bugs)
1. Clone repository (or fetch just docker-compose.yaml)
2. Create the ./secrets/basic-auth-user and password file
3. Run `docker-compose up` 
4. You will see that nats is having trouble

## Context
I've figured out the following issues/solutions so far:
* Nats is throwing the following error
`nats_1               | unrecognized command: "/nats-streaming-server"` 
  -> This can be fixed by removing the first line of command from nats in the docker-compose file
* When Nats is fixed. The other services are going to run.. Also the UI is working. But i'm not able to deploy a function using the UI. The console shows an error by calling faas-provider:8081. Also i can't find this in the docker-compose file So maybe its missing?
* In general i'm missing documentation for the docker-compose file or its not yet complete?
* Or is the purpose of this file totally different?

## Your Environment

* OS and architecture: Ubuntu 20.10 AMD64

* Versions:
As stated in the docker-compose file

Maybe you can give more insight on this docker-compose file.

Thanks

**Comment by alexellis** [comment]
Hi @eloo I'm not really sure what I can do to help here as faasd is working as expected for us.

What have you changed?

Can you say why you didn't follow our installation instructions we provide?

Alex

I'm going to close this out as technical support, feel free to join Slack and ask for help there. If there is a bug with the faasd deployment file, we will fix that (but I haven't been convinced that there is yet)

**Comment by eloo** [comment]
Hi @alexellis 
my problem is that there is an docker-compose file located in your repository which is actually not working at all.
The NATS component can not run with the provided configuration. 

I didn't follow your instructions because i couldn't anything for usage with docker. 
If you would provide how the docker-compose file can be used this would be very helpful. Or if this file is just not usable it should maybe be removed.

Thanks

**Comment by alexellis** [comment]
How are you installing faasd? Which tutorial are you following?

I would recommend either of the following:

* https://github.com/openfaas/faasd/blob/master/docs/MULTIPASS.md
* https://github.com/openfaas/faasd/blob/master/docs/bootstrap/digitalocean-terraform/README.md

Can you try one of those and confirm that it's not user-error?

Alex

**Comment by alexellis** [comment]
@eloo sorry but I've just run through the full steps of MULTIPASS.md above and it worked fine without any issues.

To help us, help you, you'll need to use an official guide to install faasd, and then tell us anything important we need to know like what platform you're running on, and anything else that emight be important.

So just to confirm: there is no issue with docker-compose.yaml when using the tutorials provided.

Alex

**Comment by Aschen** [comment]
@eloo 

I had to replace the definition of the `nats` service in order to make it work:

```
  nats:
    image: docker.io/library/nats-streaming:0.11.2
    command: "--store=memory --cluster_id=faas-cluster"
```
