### ISSUE TITLE
Protect Maximum Limit Resource Nodes

### ISSUE THREAD

**Issue by derit** [openfaas/faasd#126]
what about to mechanism to limit maximum resource per node?

for example i have a node with 4G RAM
and i can deploy a functions without have a notified when ram is 80% used?

my expectation, when ram was used 80% i want to protect nodes and disable deployment with message "system not have a resouce to deploying a function"

**Comment by alexellis** [comment]
Are you wanting to use faasd? Or something else?

faasd supports memory limits per function, so use that.

**Comment by alexellis** [comment]
Closing as a support request. Feel free to keep commenting here. Support is usually done by the community on Slack

**Comment by derit** [comment]
@alexellis  not per function this is about all resource in a instance server

**Comment by alexellis** [comment]
You can do that with openfaas on Kubernetes which will stop scheduling. For faasd you can set individual limits, but I'm not sure what happens yet if you go over.

Why are you using faasd specifically? You do know that faasd is for a single host?

**Comment by alexellis** [comment]
What workloads are you wanting to run?

**Comment by derit** [comment]
of course, i know , in my case i want to protect my single node server with limit maximum container by current resource

**Comment by alexellis** [comment]
Is this a theoretical nice to have or do you actually find this is an issue for you? Have you run into this yet?

It implies you may be running a service or automated deployments where you don't know how much you're going to need. Can you say what you're running?

**Comment by derit** [comment]
yes, your are correct, in my case i don't know how much container to running in my single server, but i want to limit by maximum server resource, for example with autoscale mode
