### ISSUE TITLE
Bug in faasd multipass tutorial: basic-auth-password file described in tutorial is missing

### ISSUE THREAD

**Issue by jakeczyz** [openfaas/faasd#127]
Hello.  In the faasd multipass tutorial here:  

https://github.com/openfaas/faasd/blob/master/docs/MULTIPASS.md 

In the final step prior to "Try faasd (OpenFaas)" the instructions call for reading the `/var/lib/faasd/secrets/basic-auth-password` file, however, the `/var/lib/faasd` directory is missing on the VM, and no such file exists.  E.g.

    root@faasd:~# find / -name 'faasd'
    /var/lib/cloud/instances/faasd

The above directory doesn't contain that file either (nor does the vm broadly).  
    
    root@faasd:/var/lib# find / -name 'basic-auth-password'
    root@faasd:/var/lib#

Any updates on where the password can now be found?   Thanks!

**Comment by alexellis** [comment]
Hi I'm not sure what you're doing differently but I ran this a few days ago and it worked fine. 

I'd suggest you look at your cloud init logs (/var/log/. Perhaps your network isn't working on your VM and couldn't execute the cloud init script.

I'm going to close the issue now as you didn't use the template and we can't reproduce the issue here. Feel free to keep commenting. 

Alex

**Comment by alexellis** [comment]
/set title: Support request for multipass tutorial

**Comment by jakeczyz** [comment]
Whoops.  Looks like none of the cloud-init steps completed successfully.  Upon further investigation, it's my environment's security solution MitM'ing the SSL connections for inspection and causing curl's SSL cert check to fail.  Derp.   Sorry for the noise, and thanks for the rapid response (and the great work on OpenFaaS! 👍)!

**Comment by alexellis** [comment]
No worries

You may enjoy my new walkthrough video on faasd https://www.youtube.com/watch?v=WX1tZoSXy8E&feature=youtu.be

I'd also suggest taking up the Community Insiders' Program. https://openfaas.com/support
