### ISSUE TITLE
Nvidia runtime for functions in faasd

### ISSUE THREAD

**Issue by jannikMetzner** [openfaas/faasd#133]
I'm trying to run a function in the nvidia runtime. I tried configuring containerd with the config.toml file. Running ```sudo ctr run --rm --gpus 0 docker.io/nvidia/cuda:9.0-base nvidia-smi nvidia-smi``` works. I'm new to faasd, so I don't quite know where the function actually runs. Can someone please provide me with some background information? 
My current assumption is that faasd spawns a new container with containerd which then is run in a runc runtime. 

## Expected Behaviour
pytorch works

## Current Behaviour
Running a python function that loads a model with pytorch

## Steps to Reproduce (for bugs)

1. Run python3-http template with pytorch 1.6.0 installed and load a model
--> results in error message that nvidia driver is not installed

## Context
Currently not able to run a function with gpu support

## Your Environment

* OS and architecture:
Ubuntu 18.04

* Versions:
containerd 1.3.5
faasd installed with installation script provided

**Comment by alexellis** [comment]
We are not Nvidia owners and don't have access to hardware, so you'll need to help us to help you. 

How about linking us to whatever documentation it is that you're following? 

Have you tested your docker image elsewhere to know if works? You should also link us to the code you're using and show how you've proven it works with containerd.

**Comment by alexellis** [comment]
Closing as inactive.
