### ISSUE TITLE
Allow functions to resolve the core services

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#134]
## Expected Behaviour

Functions should be able to resolve the core services via name, such as `gateway`

## Current Behaviour

They cannot because the provider has its own /etc/hosts file which is separate from the main faasd process.

## Possible Solution

Have the faasd process write the hosts file for the faasd-provider process, or have faasd-provider read from the faasd file.

## Steps to Reproduce (for bugs)

1. Create a new function with a language such as go
2. Attempt a HTTP GET to a container in the core services such as `http://prometheus:9090/`
3. See it fail to resolve

## Context

Generally, functions should not call other functions directly but via the gateway

Some functions like in OpenFaaS Cloud call into Prometheus directly, which wouldn't work.

The NATS connector example has a sample workload that publishes a message directly to NATS which won't work with faasd today.

**Comment by alexellis** [comment]
For anyone landing here - the ebook referenced in the README has detailed examples for this, effectively for the time being it's best to use the IP of `openfaas0` which is a stable IP of: `10.62.0.1`.

**Comment by DanielHabenicht** [comment]
Until this is merged I can highly recommend: https://willschenk.com/articles/2021/setting_up_services_with_faasd/
