### ISSUE TITLE
hack/install.sh on arm64: error undefined symbol: seccomp_api_get

### ISSUE THREAD

**Issue by vielmetti** [openfaas/faasd#144]
## Expected Behaviour

On an arm64 system, hack/install.sh should just work.

## Current Behaviour

When running `containerd`, you get this error message

```error undefined symbol: seccomp_api_get```

## Possible Solution

Get a newer version of libseccomp2 and libseccomp-dev from buster-backports, a la

https://github.com/containerd/containerd/issues/3871#issuecomment-741661018

## Steps to Reproduce (for bugs)

1. On arm64 system running Debian Buster, install faasd with hack/install.sh
2. Bring up containerd, it will fail with the `seccomp_api_get` error
3. Update the libseccomp2 and libseccomp-dev dependencies per https://github.com/containerd/containerd/issues/3871#issuecomment-741661018
4. All will be well.

## Context

Part of a longer quest to replace docker with containerd, documented at

https://vielmetti.typepad.com/logbook/2020/12/moving-from-docker-to-containerd-for-faasd.html

## Your Environment

* OS and architecture:

```
emv@pinateck:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
emv@pinateck:~ $ arch
aarch64
```

* Versions:

```sh
go version
emv@pinateck:~ $ go version
go version go1.14 linux/arm64

containerd -version

emv@pinateck:~ $ containerd -version
containerd github.com/containerd/containerd v1.3.5 9b6f3ec0307a825c38617b93ad55162b5bb94234

uname -a
emv@pinateck:~ $ uname -a
Linux pinateck 5.4.79-v8+ #1373 SMP PREEMPT Mon Nov 23 13:32:41 GMT 2020 aarch64 GNU/Linux

cat /etc/os-release
```

**Comment by MrWormHole** [comment]
Hi @vielmetti , is this still an occurring issue? I run my faasd instance in armv8(aarch64) system with debian 11.

Can you confirm if this can be closed or not?

**Comment by alexellis** [comment]
> On an arm64 system, hack/install.sh should just work.

I agree, and in my general experience, faasd works "fine" on ARM64 and I use it on Raspberry Pi OS and Ubuntu 20.04 on a regular basis. I've also used it at various times on 64-bit ARM servers from Equinix Metal.

This seems more like an issue with the specific version or distribution you're using? Could you update the heading accordingly?

What's the linked issue to containerd? Does this go away if you upgrade containerd? I am seeing you mention a very old version compared to what we use today.

Alex

**Comment by alexellis** [comment]
I've just seen this issue is two years old, so I'm going to close it. If this is an issue again for anyone, raise a new issue please.
