### ISSUE TITLE
Cannot install faasd using hack/install.sh script

### ISSUE THREAD

**Issue by hunzikerj** [openfaas/faasd#148]
## Expected Behaviour
Script should install faasd. Version should be parsed correct.
```
Finding latest version from GitHub
0.10.0
```

## Current Behaviour
Script fails because the version fetch request is not parsed correct.
```
Finding latest version from GitHub
0.10.0socket-worker-5029ae85.js
```

## Possible Solution
It seems to be the same problem as [faas-cli #856](https://github.com/openfaas/faas-cli/issues/856)

## Steps to Reproduce (for bugs)
Run install script as recommended in readme.md.
```
git clone https://github.com/openfaas/faasd
cd faasd

./hack/install.sh
```

## Your Environment
Should not affect this issue.

**Comment by alexellis** [comment]
This is related to issue https://github.com/openfaas/cli.openfaas.com/pull/6

We can produce a fix for this relatively quickly, or you can use an alternative method of installation like Terraform.
