### ISSUE TITLE
Add command for resetting auth secrets

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/faasd#16]
Currently the secrets are created if they dont exist, but they are never changed. 

We need some way for a user to easily reset secrets, and possibly reload the containers that rely on them if they are running? 

## Expected Behaviour

A command to change the saved secret, or we can recreate every time?

## Current Behaviour

Secrets static once created and dont change. A user would have to manually remove the file in the working dir
## Possible Solution

Command to remove the file? It recreate it?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* OS and architecture:

* Versions:

```sh
go version

containerd -version

uname -a

cat /etc/os-release
```

**Comment by alexellis** [comment]
I think this is working as expected. Maybe you can add a note on how to delete or edit the secret in the README?
