### ISSUE TITLE
cloud-init installation on Hetzner Cloud fails 

### ISSUE THREAD

**Issue by Sopor10** [openfaas/faasd#160]
The Ubuntu 20.04 Image on Hetzner Cloud does not have git preinstalled.

## Expected Behaviour
Add git to packages
```
packages:
 - runc
 - git
```

## Current Behaviour
cloud-init fails on 
`git clone --depth 1 --branch 0.10.2 https://github.com/openfaas/faasd`

## Your Environment

* OS and architecture:
Ubuntu 20.04 amd64 on Hetzner Cloud

**Comment by alexellis** [comment]
Happy for you to send a PR for this. Thanks for letting us know.
