### ISSUE TITLE
net.ipv4.conf.all.forwarding error

### ISSUE THREAD

**Issue by albertkohl-monotek** [openfaas/faasd#162]
## Expected Behaviour
On Ubuntu 18.04, /hack/install.sh should run with out any issues. however it fails to set ip forwarding properly.

## Current Behaviour
line # 192 in install.sh throws the error:
sysctl: permission denied on key 'net.ipv4.conf.all.forwarding'

## List all Possible Solutions
Current line Read: /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
update to: $SUDO /sbin/sysctl -w net.ipv4.conf.all.forwarding=1

tested it and all works well after this adjustment.

## Your Environment
Ubuntu 18.04 LTS

**Comment by alexellis** [comment]
Would you like to send a PR?

If it's not working then perhaps it's not necessary?

Cc @jsiebens (script author)

**Comment by albertkohl-monotek** [comment]
just submitted it. hopefully it helps someone else who ran into the same issue i did. :)

**Comment by alexellis** [comment]
(You should reference the PR here, all I can see is the commit referencing it.)
