### ISSUE TITLE
Error creating task: OCI runtime create failed: runc did not terminate sucessfully: unknown

### ISSUE THREAD

**Issue by motion-x** [openfaas/faasd#175]
I have installed FAASD on a Pi 3 using the `hack/install.sh` script. When checking the output log with `journalctl -u faasd --lines 100 -f` I see the following error:

```2021/04/19 09:22:21 Start-up order:
2021/04/19 09:22:21 - basic-auth-plugin
2021/04/19 09:22:21 - nats
2021/04/19 09:22:21 - prometheus
2021/04/19 09:22:21 - gateway
2021/04/19 09:22:21 - queue-worker
Starting: basic-auth-plugin
2021/04/19 09:22:21 Created container: basic-auth-plugin
2021/04/19 09:22:22 Error creating task: OCI runtime create failed: runc did not terminate sucessfully: unknown
Error: OCI runtime create failed: runc did not terminate sucessfully: unknown```

## Context
Error on startup after installation.

## Your Environment

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

**Comment by alexellis** [comment]
Hi @motion-x thanks for your interest in faasd.

I would like you to take a moment to fill out the whole issue template and not to delete the fields we ask for.

That'd be much appreciated.

You may also want to use Raspberry Pi OS (32-bit) as that's what we use to test on.

https://raw.githubusercontent.com/openfaas/faasd/master/.github/ISSUE_TEMPLATE.md
