### ISSUE TITLE
[Feature request] Custom DNS server address

### ISSUE THREAD

**Issue by jackrod** [openfaas/faasd#176]
## Expected Behaviour
Allow nameservers to be specified in config or as a replacement file.

## Current Behaviour
Currently the nameserver is hardcoded and does not work in my environment

## Are you a GitHub Sponsor (Yes/No?)
- [ X] No

## List all Possible Solutions
*Use a file template for nameserver
*Allow a configuration to set the nameservers

## List the one solution that you would recommend
Template resolv.conf

## Steps to Reproduce (for bugs)
Deploy Faasd to environment where DNS is not 8.8.8.8 and watch nothing work

## Context
Standalone environment with a private DNS server

## Your Environment

* OS and architecture:
Amazon Linux
* Versions:
2
```sh
go version
N/A
containerd -version
1.4.4
uname -a
N/A
cat /etc/os-release
Amazon Linux
faasd version
```latest

Is there a way to override this behavior?

https://github.com/openfaas/faasd/blob/2885bb0c514a403d317b93e6d8add1ad52239a13/cmd/provider.go#L65

Thanks,
~Jack

**Comment by alexellis** [comment]
Hi @jackrod, thanks for your interest in OpenFaaS.

Please can you fill out the whole issue template?

**Comment by jackrod** [comment]
Thanks Alex!

**Comment by jackrod** [comment]
I did it! I think?

**Comment by alexellis** [comment]
Thanks for following the contribution process, if we had started there, it might have meant getting to this point a little sooner.

> Currently the nameserver is hardcoded and does not work in my environment

Why is that? Can you help us understand so we can triage this?

Alex

**Comment by alexellis** [comment]
/set title: [Feature request] Custom DNS server address

**Comment by amarjothi** [comment]
> Thanks for following the contribution process, if we had started there, it might have meant getting to this point a little sooner.
> 
> > Currently the nameserver is hardcoded and does not work in my environment
> 
> Why is that? Can you help us understand so we can triage this?
> 
> Alex

hi Alex, 
I can answer this, faasd is deployed on an internal network with no external connectivity. Hence there is a requirement to override to set it to organizations nameserver and search. dns and dns.search parameters. Please do you know if this will be fixed any time soon.

Kind Regards,
Amar.
