### ISSUE TITLE
Populate the memory limits of functions in the REST API

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#177]
## Expected Behaviour

When users list or query functions from the REST API, then the memory limits set on the functions should be returned in the JSON response.

## Current Behaviour

They are being accepted upon deployment, but not being populated when querying.

## List all Possible Solutions

Try to read back from the task or container definition.

Update here:

https://github.com/openfaas/faasd/blob/master/pkg/provider/handlers/functions.go

https://github.com/openfaas/faasd/blob/master/pkg/provider/handlers/read.go

## Context

Required for terraform provider and API compliance.

**Comment by developer-guy** [comment]
I would like to do that, if no one wants to 🙋🏻‍♂️

**Comment by alexellis** [comment]
Given how long has passed since you volunteered to help, this issue is now fair game for anyone who wants to contribute.

Nobody is working on this at present.

**Comment by alexellis** [comment]
/add label: help wanted, good first issue

**Comment by alexellis** [comment]
@Shikachuu I don't think we have any CPU limits at this stage, so this just covers memory being populated *back again* from what was inputted.

See also: https://github.com/openfaas/faasd/commit/9e5eb84236865069396adc29d3e5855d5d42a70a
