### ISSUE TITLE
Stopping faasd and faasd-provider does not release the faasd binary

### ISSUE THREAD

**Issue by kmpm** [openfaas/faasd#179]
When trying to upgrade faasd on my RaspberryPi I stopped faasd and faasd-provider using systemctl. The services are stopped but a process is still using `/usr/local/bin/faasd` which is the binary used to run faasd.

## Expected Behaviour
When I stop `faasd.service` and `faasd-provider.service` I expect to be able to replace/upgrade faasd as described in the book.
I cant replace `/usr/local/bin/faasd` because it's in use even though the services are stopped.

## Current Behaviour

`systemctl stop` does not complain that anything went wrong when stopping the services but the faasd binary is still locked.

```shell
sudo systemctl stop faasd-provider
sudo systemctl stop faasd

sudo lsof /usr/local/bin/faasd
COMMAND  PID USER  FD   TYPE DEVICE SIZE/OFF NODE NAME
faasd   1862 root txt    REG  179,2 13107200 4796 /usr/local/bin/faasd
faasd   1980 root txt    REG  179,2 13107200 4796 /usr/local/bin/faasd
faasd   2091 root txt    REG  179,2 13107200 4796 /usr/local/bin/faasd
faasd   2207 root txt    REG  179,2 13107200 4796 /usr/local/bin/faasd
faasd   2325 root txt    REG  179,2 13107200 4796 /usr/local/bin/faasd
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No

But I bought the book :)

## List all Possible Solutions

Perhaps look at #64 and #65.

My workaround was too `kill -9` all processes that was using the file, but don't like it.

## Steps to Reproduce (for bugs)

1. Install faasd
2. Deploy some functions
3. `systemctl stop faasd && systemctl stop faasd-provider`
4. Check with `lsof`

## Context

This error makes it hard to update faasd.

Looking at the status of faasd shows that it might be prometheus that block things from stopping.
```
systemctl status faasd
● faasd.service - faasd
   Loaded: loaded (/lib/systemd/system/faasd.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2021-06-01 16:11:41 CEST; 15min ago
  Process: 1814 ExecStart=/usr/local/bin/faasd up (code=exited, status=0/SUCCESS)
 Main PID: 1814 (code=exited, status=0/SUCCESS)

jun 01 16:09:08 kmpm-faasd1 faasd[1814]: 2021/06/01 16:09:08 Proxy from: 0.0.0.0:8080, to: gateway:8080 (10.62.0.10)
jun 01 16:11:09 kmpm-faasd1 faasd[1814]: 2021/06/01 16:11:09 Signal received.. shutting down server in 1s
jun 01 16:11:09 kmpm-faasd1 faasd[1814]: 2021/06/01 16:11:09 [Delete] removing CNI network for: prometheus
jun 01 16:11:09 kmpm-faasd1 systemd[1]: Stopping faasd...
jun 01 16:11:10 kmpm-faasd1 faasd[1814]: 2021/06/01 16:11:10 [Delete] removed: prometheus from namespace: /proc/1879/ns/net, ID: prometheus-1879
jun 01 16:11:10 kmpm-faasd1 faasd[1814]: 2021/06/01 16:11:10 Status of prometheus is: running
jun 01 16:11:10 kmpm-faasd1 faasd[1814]: 2021/06/01 16:11:10 Need to kill task: prometheus
jun 01 16:11:40 kmpm-faasd1 faasd[1814]: error deleting container prometheus, prometheus, cannot delete running task prometheus: failed precondition
jun 01 16:11:41 kmpm-faasd1 systemd[1]: faasd.service: Succeeded.
jun 01 16:11:41 kmpm-faasd1 systemd[1]: Stopped faasd.
```

## Your Environment

* OS and architecture:

* Versions:

```sh
go version
go version go1.16.4 linux/arm

containerd -version
containerd github.com/containerd/containerd v1.3.5 9b6f3ec0307a825c38617b93ad55162b5bb94234

uname -a
Linux kmpm-faasd1 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

faasd version
faasd version: 0.11.3-2-g2885bb0-dirty  commit: 2885bb0c514a403d317b93e6d8add1ad52239a13
```

**Comment by alexellis** [comment]
Hi, thanks for your interest in faasd.

How long are you waiting here? faasd takes a while to clean up resources, so it doesn't exit immediately.

Alex

**Comment by alexellis** [comment]
@kmpm should we assume that you are no longer interested in technical support given that you haven't replied to the issue in several months?

Let me know within the next couple of days and we can always close this out for you.

**Comment by kmpm** [comment]
Leave the issue closed. Thanks for the effort.
Was trying to follow the book in how to upgrade faasd but I couldn't because faasd never stopped. Perhaps I should have waited longer and/or please edit the book and mention that it can take a while as well as perhaps give an example for how long it takes on a RPI4 or something.
I waited 2-3 minutes before looking into how to kill the process.
