### ISSUE TITLE
Cancel proxies when receiving sigint/term

### ISSUE THREAD

**Issue by mohammadVatandoost** [openfaas/faasd#191]
## Expected Behaviour

when receive SIGTERM or SIGINT, close the proxies socket in `func (p *Proxy) Start() error`
This also commented as ToDo in code
## Current Behaviour

It does not close the sockets before shutting down
## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## List all Possible Solutions

The idea is to close connection in proxies and finish goroutine of start method.
Add Close channel to proxy struct and, when receive sigint/term send message to each Close channel of proxies.
In Start method of Proxy, listen to Close channel. When receive message in Close channel, close connection listener and finish start function.

## List the one solution that you would recommend

Add Close channel to proxy struct and, when receive sigint/term send message to each Close channel of proxies.
In Start method of Proxy, listen to Close channel. When receive message in Close channel, close connection listener and finish start function.

## Your Environment

* OS and architecture: Ubuntu 20.04

* Versions:
1.14.2
```sh
go version
go version go1.15.6 linux/amd64

containerd -version
containerd github.com/containerd/containerd v1.5.4

uname -a
5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


faasd version
  __                     _ 
 / _| __ _  __ _ ___  __| |
| |_ / _` |/ _` / __|/ _` |
|  _| (_| | (_| \__ \ (_| |
|_|  \__,_|\__,_|___/\__,_|

faasd version: dev	commit: 
```

**Comment by alexellis** [comment]
Hi @mohammadVatandoost you'll need to fill out the whole issue template, this isn't sufficient for someone to take a look.

**Comment by alexellis** [comment]
@mohammadVatandoost please can you confirm whether you've read the comment I sent you about 2-3 weeks ago? If you've lost interest, or don't want to provide the additional information, then I would be happy for you to close the issue.

**Comment by mohammadVatandoost** [comment]
Sorry @alexellis, I was busy.
I updated description.

**Comment by alexellis** [comment]
Thanks, please could you provide details under `Steps to Reproduce (for bugs)`?
