### ISSUE TITLE
BASH faasd instance - exec: "docker": executable file not found in $PATH when deploying test script

### ISSUE THREAD

**Issue by shrike71** [openfaas/faasd#198]
## Expected Behaviour
Following book 'SERVERLESS FOR EVERYONE ELSE' with faasd. Managed to get to page 20, 'Your first JavaScript function' with no problems. The installation is bash based on a VirtualBox VM detailed below.

Trying to run 

`faas-cli up -f starbot.yml`

and expect to see:

```
Deployed. 200 OK.
URL: http://127.0.0.1:8080/function/starbot

```
## Current Behaviour

```
ubuntu@ubuntu:~/projects/code/faasd$ faas-cli up -f starbot.yml
[0] > Building starbot.
Clearing temporary build folder: ./build/starbot/
Preparing: ./starbot/ build/starbot/function
Building: starbot:latest with node12 template. Please wait..
[0] < Building starbot done in 0.02s.
[0] Worker done.

Total build time: 0.02s
Errors received during build:
- exec: "docker": executable file not found in $PATH

ubuntu@ubuntu:~/projects/code/faasd$
```

I get that you're not supposed to install a separate docker/containerd environment on the same instance as your deploying faasd server, but the book instructions imply that running `faas-cli up -f starbot.yml` after a basic template generation should deploy the script. I seem to be missing something, or should the generation happen elsewhere and be checked in somehow? The book isn't making this clear

## Your Environment

Intel i7 with 32GB RAM / 1TB SSD

    OS and architecture:
    Windows 10 Host,
    VirtualBox Version 6.1.26 r145957 (Qt5.6.2)
    Ubuntu 21.04 guest with latest updates as of 2021-08-12

    Versions:

Bash 5.1.4(1)-release

go version go1.16.5 linux/amd64

containerd -version
containerd github.com/containerd/containerd v1.5.4 69107e47a62e1d690afa2b9b1d43f8ece3ff4483

uname -a
Linux ubuntu 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute

faasd version

faasd 0.13.13

**Comment by alexellis** [comment]
You need docker on your machine and don't build functions on the faasd server. This should all my covered in the ebook. 

Build your functions on your own computer with docker and set the gateway IP to your faasd server. 

Thanks for you support.

**Comment by shrike71** [comment]
I get that if building functions through a normal CI/CD or dev operation,
you should build the functions elsewhere, as specified in your book on page
6, chapter 2.

However, I was just working through your tutorial on page 20/21 "Your first
JavaScript function"`. Up to and until this part


> If you’re building from a PC and deploying to a PC, you can run faas-cli
> up:
> faas-cli up -f starbot.yml
> Deployed. 200 OK.
> URL: http://127.0.0.1:8080/function/starbot
>
>
the documentation didn't seem to make a differentiation (I was assuming
just for learning purposes) between a build instance of a faasd
installation and a deployment instance of faasd. Does this mean i should
run two instances of faasd? One on an instance of docker/containerd
preinstalled for dev/building, and another just with faasd for deploying?

I generally use an array of VirtualBox VMs (or containers, for smaller
cases) for first building and then promoting to test. Can you explain the "
set the gateway IP to your faasd server " bit, please?

Thank you for all your help, the book and the platform are great! Having
built the docker swarm version a couple of years back, this was much more
approachable.

Regards,

**Comment by alexellis** [comment]
It's covered here at the beginning of the book:

```
# Deploy your server

In this chapter you will learn what faasd is, and when to use it instead of OpenFaaS on Kubernetes. You'll decide whether to self-host, use a Raspberry Pi, or whether to use a cloud host. You'll learn the options for installation faasd and then the pace changes in the following chapter where we start kicking the tires with the UI and creating functions.

## Why do you need a server?

Your faasd journey begins with a server. This server will run a stack of core services that make up OpenFaaS, but also gives you the ability to add stateful containers like [Postgresql](https://www.postgresql.org/) and [Minio](https://min.io) for storage. Your functions are run in their own separate stack, and will be packaged in container images.

It's easier to run faasd on a remote host than on your own computer because it requires a Linux Operating System and because it's supposed to be treated as an appliance or server that can be replaced at any time. For the same reason, you should not build your functions on the faasd server, but on your own computer or through a CI pipeline.

```
