### ISSUE TITLE
adding new stateful services to docker-compose file

### ISSUE THREAD

**Issue by krishnasaga** [openfaas/faasd#200]
Need an example in docs demonstrating adding other stateful services through its docker-compose.yaml file
as mentioned here https://github.com/openfaas/faasd#about-faasd as last point

I don't know it is appropriate to ask a question here over asking in StackOverflow
How to add new services to docker compose file, I'm trying to add minio  and kafka to the stack tried modifing the docker compose in the fork of the repo  and modifying the repoing being cloned it in cloud-config.txt  but no luck. 

## Expected Behaviour

add a simple example to add other services  like  minio, kafka etc by modifying or docker-compose or any other way.

## Current Behaviour
No example so stuck by trying my own ways

## Are you a GitHub Sponsor (No)
If could succeed creating my architecture with fassd I will surely consider

Check at: https://github.com/sponsors/openfaas
- [] Yes
- [ x] No

## List all Possible Solutions

- adding few lines of code in cloud init 
- ability to provide modified docker compose file

## List the one solution that you would recommend
- adding few lines of code in cloud init

## Steps to Reproduce (for bugs)

1. execute multipass example as described
2. how to add new services like mino and kafka -- stuck  :( 
3.
4.

## Context
As I want to have a storage like s3 and Kafka as a message broker, I'm currently stuck 

## Your Environment
Mac and multipass as explained in the example

* OS and architecture:
Mac OS

* Versions:

```sh
go version
as in multipass example 

containerd -version
as in multipass example 

uname -a
as in multipass example 

cat /etc/os-release

faasd version
as in multipass example 

```

**Comment by Shikachuu** [comment]
Hey @krishnasaga ,
You can modify the `docker-compose.yml` file as you would normally do with a few minor exceptions.
From what I tested and what the other issues/blogs and the book says, it is pretty much behaves the same as [`nerdctl`](https://github.com/containerd/nerdctl/blob/master/docs/compose.md). 

You can buy the book, there are a few chapter in it just for this use case.
(If you are on a budget you can read [this blog post](https://willschenk.com/articles/2021/setting_up_services_with_faasd/) for a high level overview and buy the book later.)

Important note, if you want to use internally deployed services (`docker-compose.yml`) from the functions scope, you probably need to wait for a merge #199. Until the merge, the blog post that I mentioned earlier using a port binding workaround which is currently working a-okay.

If you need more information about this topic feel free to ping me.

**Comment by alexellis** [comment]
Hi @Shikachuu thanks for trying to help here, but we cover this in the eBook in great depth.

The documentation is in the eBook for a reason, and is priced so that anyone can buy a copy.

Alex

**Comment by krishnasaga** [comment]
@alexellis I didn't get why the blog post link is removed :( 
And also I disagree that it is not priced as such an entry level graduate learner dong side projects cannot buy it 
For a business yes it is on budget. But for side project guys and young students it is not on the budget
More people use your software, more power it will become with use cases.   Thanks :)
