### ISSUE TITLE
Namespace not checked (exists/tagged) before deploy

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/faasd#203]
When using the non-default namespace the faas-cli deploy command with `-namespace` should validate that the supplied namespace exists and is labeled such as:

```sh 
sudo ctr namespace create dev
sudo ctr namespace label dev openfaas=true
```

## Expected Behaviour
trying to deploy to a non-existent AND/OR non tagged namespace should error
## Current Behaviour
it deploys to the non-existent or non-tagged namespace

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

## List all Possible Solutions
add a check before deploy call that checks the namespace exitst/is labeled `openfaas=true` 

## Steps to Reproduce (for bugs)

1. deploy at least 0.14.0 faasd
2. deploy to a non-existent namespace
3. profit

**Comment by alexellis** [comment]
This might affect other operations such as update and other endpoints such as the ones for secrets which also take a namespace query string.

Something like this would enable you to look up the namespace passed in, in an efficient way

```go
store := client.NamespaceService())
labels, err := store.Labels(context.Background(), targetNamespace)
if _, found := labels["openfaas"]; found {
    // labelled and valid
}
```

Based upon the code I saw in the list namespaces handler by @nitishkumar71

**Comment by alexellis** [comment]
FYI @nitishkumar71
