### ISSUE TITLE
Deploying with faasd AWS CDK

### ISSUE THREAD

**Issue by strongishllama** [openfaas/faasd#207]
Hi there!

I've translated the DigitalOcean Terraform deployment into a CDK construct so I cloud play around with it on an AWS EC2 instance. 

If you think it would be useful to the community I'd be more than happy to put in a pull request to either add the CDK construct to the docs directory of this project or just link to the NPM package once I've cleaned it up a little.

My initial thought would be the linking the package might be better because I was thinking of adding ECS/Fargate support as well and it might get a bit large to add to the docs directory.

Thanks.

**Comment by alexellis** [comment]
Hi @strongishllama I'd be interested in seeing a blog post or sample that we can run and try out.

Let me also ping @nathanpeck who wrote [some CDK for inlets and ECS Anywhere](https://github.com/nathanpeck/inlets-on-ecs-anywhere), he may also have an interest.

Alex

**Comment by strongishllama** [comment]
@alexellis sounds good. I'll clean it up a bit and send through a link to a sample project.

**Comment by strongishllama** [comment]
Hey @alexellis,

Here's a link to the [demo CDK stack](https://github.com/strongishllama/faasd-cdk-demo) and the [NPM package](https://github.com/strongishllama/faasd-cdk) it imports.

If you're looking to try it out your best bet would be to clone the demo stack and follow the deployment steps in the readme.

A couple of things to note, mainly around two assumptions I've made.
- There needs to be a Route53 hosted zone in the same AWS account and region you're deploying to, so the stack can create an A record for faasd.
- You'll also need to create a VPC manually (or just use the default one) and add the VPC ID as a property in the stack. This is to get around possible VPC cidr issues.
- You may also want to tweak your EC2 instance size and class depending on your needs, I've done very little testing under load. They're both available as optional properties.

Of course, any feedback is very welcome.

I'd also be more than happy to write up a blog post if you'd think it would be helpful. The demo stack was just a lot quicker to throw together and I wanted to make sure I was on the right track before committing too much time.

Cheers,
Taliesin

**Comment by alexellis** [comment]
Sure let me know when you have something.

**Comment by alexellis** [comment]
You can join us on [Slack](https://slack.openfaas.io) if you like, because there's some development happening on faasd and we could use your help with testing (and contributing if that's of interest)

**Comment by alexellis** [comment]
/set title: Deploying with faasd AWS CDK

**Comment by strongishllama** [comment]
Thanks, I'll check it out.
