### ISSUE TITLE
Windows Server 2022 Support for fassd

### ISSUE THREAD

**Issue by steskalja** [openfaas/faasd#210]
With CNI and containerd both supported for Windows Server, it would be great if faasd could be made to support Windows Server, staring with Windows Server 2022 

## Your Environment

OS and architecture: Windows Server x86

Versions: 2022

go version: 1.17.2

containerd version: 1.5.7

cni version: 0.8.1

**Comment by alexellis** [comment]
@steskalja closing out of inactivity. I'd still like to hear from you.
