### ISSUE TITLE
Change NATS to use disk storage and not memory

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#223]
## Expected Behaviour

Faasd async invocations should survive a crash of the NATS process.

## Current Behaviour

If the NATS process is restarted, it appears that all queued messages would be lost.

## List all Possible Solutions

Mount a directory in the compose file, and update the `--store` flag to `FILE`
```
    -st,  --store <string>               Store type: MEMORY|FILE|SQL (default: MEMORY)
          --dir <string>                 For FILE store type, this is the root directory
```

## Steps to Reproduce (for bugs)

1. Deploy a sleep function like `go-long` - set it to 5-10 seconds so you have time to carry out the test - use a callback URL to a local HTTP server or remote HTTP bin service
2. Make sure you see a message or two complete
2. Queue a number of messages with hey or curl
3. Restart faasd with `sudo systemctl restart faasd`
2. Observe missing messages

## Context

This is part of hardening work to make faasd more durable and usable in production.

**Comment by caquino** [comment]
Hi,

I'm taking a look at this issue and I have a question regarding how to proceed.

I'm using `/var/lib/faasd/nats` as the directory to store the data.

To create the directory, I'm changing `cmd/install.go`, which has two functions to handle directory creation:
- ensureWorkingDir, which will set the directory to `0644` as specified on `workingDirectoryPermission`
- ensureSecretsDir, which will set the directory to `0755` as specified on `secretDirPermission`

This directory requires to be writable, and the current option I am using to test is `ensureScretsDir` but as the name states, this function is not supposed to be used for a `data` directory.

The question is, what is the preferred way to proceed:
- create a new function `ensureDataDir` and const `dataDirPermission` to be used to this end?
- refactor both `ensureWorkingDir` and `ensureSecretsDir` to a generic `ensureDir` that accepts the required permission as an argument?

**Comment by alexellis** [comment]
You raise an important question here.

How should we manage data directories / volumes that are mounted for user containers? The existing directories are for faasd and faasd-provider, which are static and always required.

Technically speaking, NATS can be disabled and removed.

When adding Postgresql, the eBook Serverless For Everyone Else instructs the user to run mkdir / chmod / etc before adding a `postgresql` service to the compose file.

Is there a middle ground here where we don't hard-code the NATS folder, but create it during the `up` command if and only if it doesn't exist already? In that way, if someone opted to have a volume for Prometheus (which may be the next task here) then it'd work without any more hard-coded calls to `ensureDirectory`.

**Comment by LucasRoesler** [comment]
RE @alexellis's middle ground, I definitely prefer not requiring many "setup" steps prior to starting faasd. 

RE @caquino's question about the function, I prefer the generic function `ensureDir(name string, permissions int)` with some predefined common constants for the permissions.

I think the idea solution is to actually ensure the directories [based on the volumes in the `docker-compose.yaml`](https://github.com/openfaas/faasd/blob/master/docker-compose.yaml). For each bind mount, ensure the `source` exists or create it as a directory.  The spec is here https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json#L395-L446

Specifically this section: https://github.com/compose-spec/compose-spec/blob/a5a952ea97577169fff9f0b26854a9d92c3437ee/schema/compose-spec.json#L400-L425  Based on this there is a `read_only` property that can be used so that the compose file can even control the distinction between setting `rw` and `r`.

**Comment by caquino** [comment]
@LucasRoesler @alexellis considering the conversation we are having on #225 looks like the best option would be to not have any reference to the nats persistency directory inside of code as this would force nats to run on the same server as `faasd`.

It would be interesting if we could manage 100% of the creating/permission of the data folders only on `docker-compose.yaml` this way allowing users to extract this to other servers if they are interested in having redundancy/failover.

If I understood @LucasRoesler correctly this was his proposal also, is that correct?

**Comment by alexellis** [comment]
> I think the idea solution is to actually ensure the directories based on the volumes in the docker-compose.yaml. For each bind mount, ensure the source exists or create it as a directory. 

@caquino please can keep a copy of that branch you made with your current work, and create a new one from master. In the new branch, implement what Lucas said above.

We already have the data parsed, so the task would be to run the equivalent of the "ensure directory" function using the data from compose. Leave the current "ensure directory" references in place for faasd/faas-provider.

#225 is a separate discussion and I don't think it prevents us making this change.

**Comment by caquino** [comment]
Question about the implementation, we want `volumes` to be a install time or runtime dependency?

Should it be on cmd/install.go, or to move to an approach similar to the proxied services on cmd/up.go? e.g: on up to iteract over the volumes for all services and guarantee that the configuration on docker-compose.yaml is applied?

**Comment by alexellis** [comment]
I am not sure it makes sense during the installation. Isn't the compose file only parsed at up?

Also, install is one-time, up is run on every reboot or restart of faasd.

**Comment by alexellis** [comment]
@caquino please could you send a PR?

**Comment by alexellis** [comment]
@caquino do you need us to find someone else to pick up this work?

It's been several weeks since I last heard from you, what's your status?

**Comment by alexellis** [comment]
This is now no longer being worked on. I'm looking for a volunteer.

**Comment by Shikachuu** [comment]
I can work on this with an ETA of 12.18 Saturday-ish
