### ISSUE TITLE
HA / resilience in faasd

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#225]
## Research / request for comment

faasd was originally written as an "appliance" to run on a VM or Raspberry Pi, with low resource constraints, fast cold-starts and low-operational complexity. There is no well-defined strategy or approach for either High Availability or resilience in faasd.

Does this prevent certain users from putting faasd into production or using it for their side hustle/projects?

If you use faasd today, what is your plan? Have you tested it? Do you already have a strategy here?

## Options / ideas

Kubernetes uses etcd and the Raft consensus model. This requires at least N nodes + 1 where the total is an odd number, so that N failures can be tolerated. etcd barely works on Raspberry Pi due to the stringent timeouts it uses for writes.

Darren Shepherd also mentioned to me that etcd causes a large amount of writes to SD cards, which obviously reduces their useful lifespan.

Given that faasd has low resource requirements and suits IoT devices, does mandating etcd and 3-5 nodes, and fast storage (SSDs) make sense?

Keepalived is/was used by DigitalOcean to build their managed load balancer instances. Keepalived can run in a pair of servers, both of which have a mirrored configuration, but only one receives traffic. In the event of a failure of the Active server, the Passive server takes over, this is called Active/Passive.

Why would Active/Passive not work for faasd?

If a multi-node cluster is required, with scheduling and orchestration then K3s makes a good alternative.

faasd is designed as an appliance to run functions. The aim of this work would be to make it more resilient, so it can tolerate at least one failure before causing downtime.

I'd like to hear from the community - do you use faasd at work? What would prevent you from doing that? Is resilience important to you?

What's your plan if your single faasd instance crashes or gets compromised in some way?

**Comment by alexellis** [comment]
@dirien @vshymanskyy I see you left an emoji, but I'm interested in some answers to these questions. Do you use faasd currently and also have an opinion on what your needs are?

**Comment by caquino** [comment]
I am curious about what kind of stateful workload would require HA, maybe I'm missing something here but if on your infrastructure, moving prometheus to a dedicated cluster with your required availability model, and the same for nats, would not cover all requirements for HA and also allow multiple faasd nodes to use the same prometheus and nats backends?

I think my only concern would be if we use metrics anywhere in the system without filtering/grouping by host and if we use something that may have conflict on nats? (which is unlikely)

**Comment by alexellis** [comment]
> if you move prometheus to a dedicated cluster with your required availability model, and the same for nats, would not cover all requirements for HA and also allow multiple faasd nodes to use the same prometheus and nats backends?

I hadn't yet considered NATS and Prometheus, but thanks for bringing it up.

I think that losing a Prometheus instance would be tolerable, so long as another was ready to come online.

Losing a NATS instance could mean a loss of queued invocations, so that brings up something I hadn't considered in the original issue.

> Load Balancer -> as many faasd instances as needed -> external prometheus/nats clusters with HA/clustering

We talked about part 2, what about part 1? Load Balancer and > 1 instance.

How are you going to manage that?

@caquino "I am curious about what kind of stateful workload is running on top of faasd that would require HA."

The question is really about resilience. Do you really want your eggs in one basket? Do you really want only one server / VM and when it crashes, your users get downtime?

faasd has no built-in replication or mirroring, so if you want to run multiple faasd instances with the exact same configuration, you're going to have to manage that yourself.

How? Perhaps your CD pipeline does a deploy to each individual IP within the group of your identical faasd instances?

**Comment by caquino** [comment]
> The question is really about resilience. Do you really want your eggs in one basket? Do you really want only one server / VM and when it crashes, your users get downtime?
> 
> faasd has no built-in replication or mirroring, so if you want to run multiple faasd instances with the exact same configuration, you're going to have to manage that yourself.
> 
> How? Perhaps your CD pipeline does a deploy to each individual IP within the group of your identical faasd instances?

There are many ways to do that, let me do an exercise and imagine how I would do with the current architecture:

1. Move NATS to a stand-alone cluster 
2. Move Prometheus to a stand-alone cluster
3. Make an AMI using Packer with `faasd` pre-installed and configured to access the external NATS and Prometheus clusters
4. Create the terraform code to provision the required infra, including VPC/netblocks/etc
5. Create the terraform code to provision the `faasd` hostgroup composed of NLB -> faasd autoscaling group

As we are using autoscaling group for faasd, we can leverage health checks to replace faulty instances, and also we can deploy new AMIs and do rolling restarts to deploy new versions of the faasd AMI.

There are many variations of this, we could use chef/ansible/anything to deploy this infrastructure, this was just an example.

I'm sure this is not by any means a complete recipe and that I missed a lot of things.

**Comment by mhgoldman** [comment]
> How would we go about deploying functions? can we create the image with the list of functions but without the images? this way it can download on startup time?

I've been thinking about this problem for a project I'm working on -- namely, that the need to explicitly "deploy" a function is a kind of statefulness that might be convenient to do without sometimes. If my faasd VM acts up, it'd be nice to be able to just kill it and spin up a new one and have it be ready to go.

If I can `docker run` an image I haven't `pull`ed yet, it might be nice to be able to do something similar with faasd. Maybe I could invoke a faasd function I haven't deployed yet and have it provision on the fly, then invoke. The image name could be inferred from the function name specified (or explicitly with a separate API param). The first invocation would be slow, of course, just as with `docker run`, but if you're running things async it's likely fine. I've actually been thinking about putting my own API in front of faasd to do this.

Obviously secrets and other things introduce statefulness too -- but at least using secrets is a choice (we can always pass them as arguments to the function).

**Comment by MrWormHole** [comment]
I don't think there is any choice for faasd to have HA, you will basically have to migrate to openfaas which is the core project on top of k3s nodes in a cloud provider or in your own machines. K3S community mentions HA as 3 master nodes 3 worker nodes.

Faasd's resilience is as reliable as getting a VM and putting a container in it and if it fails you have to restart over or supply extra RAM and get scaling VM groups on top of load balancers until this gets incredible hard to manage manually. That's the moment where openfaas and k3s shine

As far as everyone's concern: I will be worried about cold starts since I have never migrated to openfaas from faasd

**Comment by alexellis** [comment]
Thanks to everyone who commented. We talked about this on the contribtutors' call this week and it seems like a generic solution might be too much work, with no current users expressing a need for this.

Feel free to keep the conversation going if you have thoughts.
