### ISSUE TITLE
faas-cli login fails after installation

### ISSUE THREAD

**Issue by darenwatkins** [openfaas/faasd#230]
After setting up a vanilla Linux VM in Azure, it first failed to let me curl to the gateway, but after restarting faasd (as recommended in the known issues section) I was able to get a response.  The next step was to log into faas-cli using this command:

 sudo cat /var/lib/faasd/secrets/basic-auth-password | ./faas-cli login -s

This resulted in

Calling the OpenFaaS server to validate the credentials...
Server returned unexpected status code: 500 - List functions responded with code 401

After extensive googling, I cannot find anyone else having this issue, nor can I find any way in which I can obtain any debug to indicate what the error is.

Any help would be appreciated!  Thanks

## Expected Behaviour
Successful log in

## Current Behaviour
An error message saying:

Calling the OpenFaaS server to validate the credentials...
Server returned unexpected status code: 500 - List functions responded with code 401

## Are you a GitHub Sponsor (Yes/No?) 

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ X] No

## List the one solution that you would recommend
A verbose mode so that more information can be obtained independently

## Your Environment
Azure hosted VM

* OS and architecture:
*Linux : Red Hat Enterprise Linux Server 7.9 (Maipo)

* Versions:

```sh
go version

containerd -version
1.5.4

uname -a

cat /etc/os-release

faasd version0.14.4

**Comment by alexellis** [comment]
Hi @darenwatkins

Thanks for your interest in faasd.

> it first failed to let me curl to the gateway, but after restarting faasd (as recommended in the known issues section)

I'm not aware of any issue where faasd would fail after installation.

> nor can I find any way in which I can obtain any debug to indicate what the error is.

There's full troubleshooting instructions in the handbook/eBook for faasd. faasd is self-service, and you should find what you need in its handbook:

https://store.openfaas.com/l/serverless-for-everyone-else

> Linux : Red Hat Enterprise Linux Server 7.9 (Maipo)

This is an open source project and we don't deploy commercial Linux operating systems like RHEL, so won't be able to give free community support on this.

I would suggest using Ubuntu Linux 20.04 LTS. That's what I use and I set this up a couple of days ago without error.

Alex
