### ISSUE TITLE
How can I enter the dashboard

### ISSUE THREAD

**Issue by LinYKen** [openfaas/faasd#234]
## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ x ] No

## Steps to Reproduce (for bugs)

It's not a bug.

## Context

openfaas is new to me. I am trying to deploy an openfaas on my virtual machine. I follow the instructions and use the install.sh under /hack to install the program. I successfully install that but I have a few questions. I managed to enter the dashboard. But what about the metrics data of Prometheus? How can I view the prometheus metrics at the address ip:9090?
I read the code in faas gateway, and try the port 8082, but the pages of /metrics and /healthz is not found. No program is listening on the port 8082.

## Your Environment

* OS and architecture:
* Ubuntu 20.04

* Versions:

```sh
go version

containerd -version

uname -a

cat /etc/os-release

faasd version
```

**Comment by alexellis** [comment]
Hi @LinYKen thanks for using faasd and thank you for asking this question.

Everything is explained including this in the official handbook for faasd.

You may benefit from owning a copy!

https://openfaas.gumroad.com/l/serverless-for-everyone-else
