### ISSUE TITLE
Image missing in faas-cli describe output.

### ISSUE THREAD

**Issue by welteki** [openfaas/faasd#245]
## Due diligence

Before you for help or support, make sure that you've [consulted the faasd manual "Serverless For Everyone Else"](https://openfaas.gumroad.com/l/serverless-for-everyone-else).

## Expected Behaviour

Image should be displayed in `faas-cli describe` output.

## Current Behaviour

Image is not displayed in `faas-cli describe` output.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* OS and architecture: x86_64 NixOS

* Versions:

```sh
$go version

$containerd -version
containerd github.com/containerd/containerd v1.5.7 v1.5.7

$uname -a
Linux nixos 5.10.81 #1-NixOS SMP Sun Nov 21 12:46:37 UTC 2021 x86_64 GNU/Linux

$cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="21.11 (Porcupine)"
VERSION_CODENAME=porcupine
VERSION_ID="21.11"
BUILD_ID="21.11pre-git"
PRETTY_NAME="NixOS 21.11 (Porcupine)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"

$faasd version
version:       0.14.4 
sha:           8fbdd1a461196520de75fe35ac0b5bdda6403ac7
```

**Comment by welteki** [comment]
> Could you or @nitishkumar71 run the [certifier](https://github.com/openfaas/certifier) against faasd please and see if the image comparison fails or is skipped?
> 
> What do you get with the HTTP API? /system/functions /system/function/NAME <- one may be lacking the image, when the other has it present?

 /system/functions has the image name, in system/function/NAME it is missing.

**Comment by welteki** [comment]
Still need to figure out why this was not detected by the certifier.

**Comment by nitishkumar71** [comment]
Since certifier do not test using `system/function/NAME` i.e. **Replica Reader**. It actually validate details from ` /system/functions` i.e. ** Function Reader**

**Comment by alexellis** [comment]
@nitishkumar71 can you log an issue so that we check the `system/function/NAME` endpoint in the certifier tests?
