### ISSUE TITLE
Normalize image name of services.

### ISSUE THREAD

**Issue by welteki** [openfaas/faasd#247]
## Due diligence

Before you for help or support, make sure that you've [consulted the faasd manual "Serverless For Everyone Else"](https://openfaas.gumroad.com/l/serverless-for-everyone-else).

faasd normalizes the image name of function deployments using `reference.ParseNormalizedNamed`. It does not normalize the image name of services defined in the docker-compose.yaml file.

Is there a reason for this?

This can be inconvenient when not using an image registry. When importing images using  e.g. `ctr image import` the image name is normalized. While it is possible to use the familiar name of an image for function deployments, services in the docker-compose.yaml file have to use the fully qualified reference.

e.g. An image imported with ctr that has a familiar name `figlet:latest` can be referenced in a function deployment as `figlet:latest`. In the docker-compose.yaml it has to be referenced as `docker.io/library/figlet:latest`

## Expected Behaviour

Normalize the image name of services in the docker-compose.yaml file.

## Current Behaviour

The image name of services is not normalized.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List the one solution that you would recommend

Normalize the image name in the supervisor client Start before calling `service.PrepareImage`

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Context

I discovered this while working on a feature for [faasd-nix](https://github.com/welteki/faasd-nix/). Nix has great support for building docker images. When deploying faasd on NixOS users might use a configuration that looks something like this:
```nix
{pkgs, ... }: 
let
  figlet-fn = pkgs.ofTools.buildOfImage {
    name = "figlet";
    tag = "latest";

    fprocess = "${pkgs.pkgsStatic.figlet}/bin/figlet";
  };
in
{
  services.faasd.enable = true;

  services.faasd.pullPolicy = "IfNotPresent";
  
  services.faasd.containers.figlet = {
    image = "figlet:latest";
    imageFile = figlet-fn;

    cap_add = [ "CAP_NET_RAW" ];
    ports = [ "6000:8080" ];
  };
}
```

When rebuilding their NixOS system `faasd` will be deployed, the `figlet-fn` image will be built and automatically imported using `ctr`. The `figlet-fn` image will be run as a service on faasd.

Currently the `image` attribute has to be set to `docker.io/library/figlet:latest` for the deployment to succeed.
It is possible to just normalize the image names in faasd-nix but I think that consistency between how function deployments and services can have images referenced is a good thing.

## Your Environment

* OS and architecture:

* Versions:

```sh
go version

containerd -version

uname -a

cat /etc/os-release

faasd version

version:       0.14.4 
sha:           8fbdd1a461196520de75fe35ac0b5bdda6403ac7
```

**Comment by alexellis** [comment]
Please go ahead with your suggestion. Thanks for reporting it.

**Comment by alexellis** [comment]
@welteki whenever you're ready feel free to send a PR, or we can close this as #wontfix. I don't mind whichever you decide.
