### ISSUE TITLE
When starting up, show downloaded images in megabytes

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#251]
## Current Behaviour

```
Mar 24 20:48:52 faasd-pi faasd[8578]: Preparing grafana with image: docker.io/grafana/grafana:latest
Mar 24 20:48:52 faasd-pi faasd[8578]: Prepare done for: docker.io/grafana/grafana:latest, 79599922 bytes
```

## Expected Behaviour

I think this would be more readable in megabytes

Such as: 79.599922 MB or 79.59 MB

## List all Possible Solutions

1) Just divide by 1024 * 1024
2) Use a library function like https://yourbasic.org/golang/formatting-byte-size-to-human-readable-format/

## List the one solution that you would recommend

Not sure

## Steps to Reproduce (for bugs)

1. These logs are printed when faasd starts up or when you restart the systemd unit file

**Comment by welteki** [comment]
I will work on this.

**Comment by alexellis** [comment]
See comment here @welteki and thank you :slightly_smiling_face:  

https://github.com/openfaas/faasd/issues/252#issuecomment-1080364137
