### ISSUE TITLE
Support GPUs option when create a function that need GPUs

### ISSUE THREAD

**Issue by merlinvn** [openfaas/faasd#254]
Hi, I'm trying to run faasd with Jetson Nano. So far my image can run with containerd in cli with the command:

` sudo ctr run --rm --net-host --gpus 0 docker.io/merlinvn/image-classy:0.1 image-classy`

But it cannot deploy to faasd due to missing `--gpus 0` tag when create a new container . Is there anyway to add options when create a new cointainer when deploying function?

I think a small patch in the `pkg/provider/handlers/deploy.go` should work, but I'm not a go developer.

` containerd.WithNewSpec(  ...... , nvidia.WithGPUs(nvidia.WithDevices([0,1,2]...), nvidia.WithAllCapabilities)))`

**Comment by alexellis** [comment]
Hi @merlinvn we will need you to fill out the [whole issue template here](https://raw.githubusercontent.com/openfaas/faasd/master/.github/ISSUE_TEMPLATE.md). If you don't want to, then I understand and can close the issue for you.

We do not have specific funding to do this work for you at this time, however, you're welcome to fork faasd under the terms of its license and to play with it on your own time. 

If you did want to make this more likely to get picked up or considered by someone, you'd need to provide: some sample code that can run and access the GPU, all the commands to configure a PC or cloud instance with an Nvidia GPU and / or a Jetson Nano, plus all the configuration for containerd. I've looked into this in the past, and containerd needs specific configurations, beyond just a couple of lines of Go.

Alex

**Comment by alexellis** [comment]
Closing due to lack of information. Happy to re-open if you fill out the issue template. See my response above from two months ago. 

https://raw.githubusercontent.com/openfaas/faasd/master/.github/ISSUE_TEMPLATE.md
