### ISSUE TITLE
GPIO accessible on RPI from faasd function?

### ISSUE THREAD

**Issue by apmontgomery** [openfaas/faasd#257]
## Expected Behaviour
It would be awesome to be able to access GPIO on raspberry pi from within 

## Current Behaviour
There seems to be no way to do so. I tried both pigpio and onoff npm libraries after modifying the template dockerfile to add relevant dependencies. 

Do you know of any workaround to achieve this?

**Comment by alexellis** [comment]
Hi @apmontgomery 

It depends what you mean by "access GPIO"? Which library are you wanting to use, and what is the application of this?

I can probably suggest a patch for you to apply for your own private usage.

Given that this is just a way of you asking for technical support, I'm going to close the issue. Feel free to continue the discussion with me here.

Alex

**Comment by apmontgomery** [comment]
A patch as suggested would be helpful. Thanks! I wrote my functions in node and tried _onoff_ and _pigpio_ as well as writing directly to _sys/class/gpio_. What would you suggest?
