### ISSUE TITLE
DigitalOcean with Terraform and faasd doesn't execute the install script

### ISSUE THREAD

**Issue by koffeinfrei** [openfaas/faasd#265]
## Why do you need this?

Following the blogpost https://www.openfaas.com/blog/faasd-tls-terraform/ I can't setup a faasd droplet on DigitalOcean.

## Expected Behaviour

After executing `terraform apply -var-file=main.tfvars` the droplet should be set up.

## Current Behaviour

After executing `terraform apply -var-file=main.tfvars` the droplet is not ready. faasd and caddy etc. are missing from the droplet.

## Are you a GitHub Sponsor (Yes/No?)
Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds

```diff
diff --git a/docs/bootstrap/digitalocean-terraform/cloud-config.tpl b/docs/bootstrap/digitalocean-terraform/cloud-config.tpl
index fdb2fc8..5594f6b 100644
--- a/docs/bootstrap/digitalocean-terraform/cloud-config.tpl
+++ b/docs/bootstrap/digitalocean-terraform/cloud-config.tpl
@@ -6,4 +6,4 @@ echo ${gw_password} > /var/lib/faasd/secrets/basic-auth-password
 export FAASD_DOMAIN=${faasd_domain_name}
 export LETSENCRYPT_EMAIL=${letsencrypt_email}
 
-curl -sfL https://raw.githubusercontent.com/openfaas/faasd/master/hack/install.sh | sh -s -
+curl -sfL https://raw.githubusercontent.com/openfaas/faasd/master/hack/install.sh | bash -s -
```

## Which Solution Do You Recommend?
:point_up: 

## Steps to Reproduce (for bugs)
1. Follow https://www.openfaas.com/blog/faasd-tls-terraform/
2. `terraform apply` outputs `Apply complete! Resources: 1 added, 0 changed, 0 destroyed.`
3. When logging in to the droplet console there's no faas or caddy process running (e.g. `ps aux | grep faas`)
4. Executing the main install part of the `cloud-config.tpl` file manually:
    ```sh
    root@faasd:~# curl -sfL https://raw.githubusercontent.com/openfaas/faasd/master/hack/install.sh | sh -s -
    sh: 5: set: Illegal option -o pipefail
    (23) Failed writing body
    ```

The issue seems to be the default shell `dash` which doesn't recognize the `set` instruction.
The script already has the explicit bash shebang. Using `bash` instead of `sh` would fix the issue (see above).

**Comment by alexellis** [comment]
Hi @koffeinfrei 

Thanks for flagging this.

I agree that this should be using bash and was missed in #218

@jsiebens this may affect the terraform providers that you maintain? cc #250

**Comment by alexellis** [comment]
Could you retest please?

@cohix you also mentioned this, it looks like it was picked up already.

Was there an issue with the M1 and the provider we use somewhere?

**Comment by jsiebens** [comment]
> @jsiebens this may affect the terraform providers that you maintain?

yes it might, I will patch them accordingly :+1:

**Comment by koffeinfrei** [comment]
> Could you retest please?
> 

Works! :+1:

Thanks for fixing this! :pray:
