### ISSUE TITLE
Install scripts fails when executed in a VM cloud-init startup script

### ISSUE THREAD

**Issue by jsiebens** [openfaas/faasd#282]
## Why do you need this?

I'm using the `hack/install.sh` in several Terraform modules to provision a faasd instance.
Recently, this started failing with the error:

```
Error: env-var HOME, not set
```
 

## Expected Behaviour

The `hack/install.sh` script should run successfully when executed from a cloud-init startup script.

## Current Behaviour

The `hack/install.sh` scripts fails when executed from a cloud-init startup script with the following error:

```
...
Downloading: https://github.com/openfaas/faas-cli/releases/download/>
/tmp/faas-cli written.
2022/06/07 13:45:28 Looking up version for faas-cli
2022/06/07 13:45:28 Found: 0.14.2
Error: env-var HOME, not set
...
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

## List All Possible Solutions and Workarounds

Haven't thought about this yet, but will try to have a closer look at it as soon as possible

## Steps to Reproduce (for bugs)

I was able to reproduce this issue with [lima](https://github.com/lima-vm/lima):

After installing lima, create a vm with the faasd example (it uses the `hack/install.sh` script in cloud-init):

```
limactl start template://faasd
```

The launch will not succeed.
Execute shell in Lima:

```
limactl shell faasd
```

And verify installation:

```
ubuntu@lima-faasd:~$ systemctl status faasd
Unit faasd.service could not be found.

ubuntu@lima-faasd:~$ sudo journalctl -u cloud-final.service
Jun 07 13:44:43 lima-faasd systemd[1]: Starting Execute cloud user/final scripts...
Jun 07 13:44:43 lima-faasd cloud-init[1944]: Cloud-init v. 22.1-14-g2e17a0d6-0ubuntu1~22.04.5 running 'modules:fi>
...
Jun 07 13:45:26 lima-faasd cloud-init[1944]: Downloading: faas-cli
Jun 07 13:45:26 lima-faasd cloud-init[1944]: 2022/06/07 13:45:26 Looking up version for faas-cli
Jun 07 13:45:26 lima-faasd cloud-init[1944]: 2022/06/07 13:45:26 Found: 0.14.2
Jun 07 13:45:26 lima-faasd cloud-init[1944]: Downloading: https://github.com/openfaas/faas-cli/releases/download/>
Jun 07 13:45:28 lima-faasd cloud-init[1944]: /tmp/faas-cli written.
Jun 07 13:45:28 lima-faasd cloud-init[1944]: 2022/06/07 13:45:28 Looking up version for faas-cli
Jun 07 13:45:28 lima-faasd cloud-init[1944]: 2022/06/07 13:45:28 Found: 0.14.2
Jun 07 13:45:28 lima-faasd cloud-init[1944]: Error: env-var HOME, not set
Jun 07 13:45:28 lima-faasd cloud-init[1944]: LIMA| WARNING: Failed to execute /mnt/lima-cidata/provision.system/0>
Jun 07 13:45:28 lima-faasd cloud-init[1944]: LIMA| Exiting with code 1
...
Jun 07 13:45:28 lima-faasd cloud-init[1944]: Cloud-init v. 22.1-14-g2e17a0d6-0ubuntu1~22.04.5 finished at Tue, 07>
Jun 07 13:45:28 lima-faasd systemd[1]: cloud-final.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 13:45:28 lima-faasd systemd[1]: cloud-final.service: Failed with result 'exit-code'.
Jun 07 13:45:28 lima-faasd systemd[1]: Failed to start Execute cloud user/final scripts.
Jun 07 13:45:28 lima-faasd systemd[1]: cloud-final.service: Consumed 18.206s CPU time.
```

I'm seeing the same error when creating a VM on GCP with Terraform ([terraform-google-faasd](https://github.com/jsiebens/terraform-google-faasd))

Possibly related: jsiebens/terraform-aws-faasd#1

## Your Environment

* OS and architecture: Ubuntu Server 22.04 (amd64)

**Comment by alexellis** [comment]
I'm a bit surprised that this usecase didn't work cc @welteki @rgee0 

Given that arkade is running as root, can you set the path to /usr/local/bin directly?

Or does arkade never work when HOME isn't set? Why don't we see this on other clouds?

**Comment by rgee0** [comment]
This is where the message is originating from:

https://github.com/alexellis/arkade/blob/master/pkg/config/config.go#L24

Reading the code around that suggests it will always fail when HOME isn't set.

Once thats fixed the next line of hack/install.sh is probably going to barf for the same reason:

https://github.com/openfaas/faasd/blob/master/hack/install.sh#L156

**Comment by jsiebens** [comment]
> Or does arkade never work when HOME isn't set? Why don't we see this on other clouds?

I think HOME isn't set when cloud-init executes a startup script.
When logging into a cloud vm after boot, the install script works as expected.
