### ISSUE TITLE
Using $SUDO instead of sudo in install.sh

### ISSUE THREAD

**Issue by Yoshino-s** [openfaas/faasd#285]
## Why do you need this?
We use $SUDO in other place, but why we use sudo only in here?

## Expected Behaviour
```sh
install_arkade(){
  curl -sLS https://get.arkade.dev | $SUDO sh
  arkade --help
}
```

## Current Behaviour
```sh
install_arkade(){
  curl -sLS https://get.arkade.dev | sudo sh
  arkade --help
}
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds

Just replace it will be fine.

**Comment by alexellis** [comment]
Thanks for letting us know.
