### ISSUE TITLE
Caddy does not start after deployment via Terraform

### ISSUE THREAD

**Issue by recumbentbirder** [openfaas/faasd#299]
## Expected Behaviour

caddy.service should run

## Current Behaviour

caddy.service does not run: can't find its binary.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

But for now, I at least just bought the book ;-)

## List All Possible Solutions and Workarounds

1. change systemd script to call caddy in /usr/local/bin
2. OR: install caddy to /usr/bin, where expected by systemd script

## Which Solution Do You Recommend?

Solution 1. already implemented by Alex in commit 13304fa0b2f549e46f3ee89f34e76287958d74b1.

**Comment by recumbentbirder** [comment]
Thanks for the fast fix, Alex!

**Comment by alexellis** [comment]
Thanks for letting us know

https://github.com/openfaas/faasd/commit/13304fa0b2f549e46f3ee89f34e76287958d74b1
