### ISSUE TITLE
I face to a very big IP connect problem, I need you help

### ISSUE THREAD

**Issue by QWQyyy** [openfaas/faasd#300]
this is a install problem
I couldn't start the queue-worker, I think it is my k8s some problem, but it seemly weel, could you give me some suggestion? 

![image](https://user-images.githubusercontent.com/54056797/185731868-4943dda2-7787-4c65-bcb4-4582379cc686.png)

![image](https://user-images.githubusercontent.com/54056797/185731876-fb2abff2-e1d3-4a77-b91a-13d79178f134.png)

![image](https://user-images.githubusercontent.com/54056797/185731883-8d0e1d3d-0408-41a4-b3ba-0f975741f13e.png)

![image](https://user-images.githubusercontent.com/54056797/185731899-9d421ceb-1d36-46c8-b38c-d70d5be35350.png)

## Your Environment

* OS and architecture:
Linux CentOS7
K8s v1.22.4

```

**Comment by QWQyyy** [comment]
port 10250 look like good, we should set some setting?

**Comment by alexellis** [comment]
Hi this is the wrong repository for whatever you're trying to do, and you've not filled in the issue template, which means we can't help you.

You may want openfaas/faas-netes, but you need to take the time to fill out every question.

Alex
