### ISSUE TITLE
Where can I find out about faasd design choices?

### ISSUE THREAD

**Issue by zhulik** [openfaas/faasd#307]
## My actions before raising this issue

I was looking for simple tool to run cloud functions on my own hardware and found faasd. The faasd readme says that it is exactly what I need, and suggest buying a manual. What it does not say about, is the fact that faasd cannot run more than one replica of a function at a time. This fact is only mentioned in the paid manual and I find it unfair.

To me impossibility to run multiple replicas of a function is a showstopper and if it was explicitly mentioned in the readme, I wouldn't invest my time and money into learning faasd, it would be obvious it didn't fit my requirements.

## Why do you need this?

Impossibility to serve multiple requests in parallel with one function makes faasd useless even for small scale apps. 
Even if I have a 64 core server, I can't utilize all it's cores and memory without manually deploying 64 functions with the same image and tinkering with caddy.

I'm not asking for a refund or so, instead I'm asking to reflect this fact in the readme so anyone interested in faasd would know what to expect.

On the other hand it would be even better to make it possible to run multiple replicas.

## Expected Behaviour

Faasd runs multiple replicas of a function within one node. The limit is configurable by the user. It must be achievable, but I'm not sure how difficult it would be.

## Current Behaviour

Faasd runs at most one replica of a function.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* OS and architecture:

* Versions:

```sh
go version

containerd -version

uname -a

cat /etc/os-release

faasd version
```

**Comment by alexellis** [comment]
Hi @zhulik thanks for your interest in faasd.

If you need scaling of replicas, then you should use OpenFaaS on K3s or Kubernetes. K3s installed with K3sup is trivial to set up and shouldn't take you more than 5-10 minutes.

We ran through this demo on our free weekly community call last week. Maintenance tasks with k3s are also much easier than "full K8s". 

> instead I'm asking to reflect this fact in the readme so anyone interested in faasd would know what to expect.

And yes, this is fully documented and in no way hidden from users:

https://github.com/openfaas/faasd/blob/master/docs/ROADMAP.md

The roadmap which is linked from the README mentions all imitations and decision decisions.

![Screenshot from 2022-10-04 15-57-35](https://user-images.githubusercontent.com/6358735/193853569-e10401f6-7ecc-4e38-9602-a242b74f57ee.png)

The eBook is a manual for faasd, but full of examples in Node.js which also work on OpenFaaS on Kubernetes.

> Even if I have a 64 core server, I can't utilize all it's cores and memory without manually deploying 64 functions with the same image and tinkering with caddy.

That's not strictly true, your functions will actually be able to consume a large, unbounded amount of resources, unless you set limits on them in the function spec. You are also free to deploy a function multiple times under different names and load-balance between them yourself.

Regards,

Alex

**Comment by alexellis** [comment]
/set title: Where can I find out about faasd design choices?
