### ISSUE TITLE
[Debug help] Function respond 200 but client receive 500

### ISSUE THREAD

**Issue by vnourdin** [openfaas/faasd#309]
## Due diligence
I have a long-running function that take 50s and then respond 200, but the client receives a 500 `Can't reach service for: my-function.namespace.`

## My actions before raising this issue
- Check the troubleshooting chapter of SfEE
- tune timeouts of gateway to 180s
- tune exec_timeout of my function to 60s

## Expected Behaviour
The function's answer should reach the client without being modified or invalidated by faasd.
If this is a timeout problem, the function should be interrupted instead of finishing its job normally.

## Current Behaviour
- the function finish as expected `08:41:57 GET / - 200 OK - ContentLength: 8B (49.0651s)`
- the client receives a 500 `Can't reach service for: my-function.namespace.`
- There is no error log on the function logs
- in `faasd-provider` logs I have the following error `08:41:57 error with proxy request to: http://10.62.3.247:8080, Get "http://10.62.3.247:8080": EOF`

## Are you a GitHub Sponsor (Yes/No?)
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds
No idea of workaround nor solution, I'm looking for help to investigate and find out what's happening.

## Steps to Reproduce (for bugs)
I have other long-running functions working well, son I don't know how to reproduce.

## Your Environment

* OS and architecture: Debian bullseye 5.10.149-2 x86_64
* containerd: v1.6.8
* faasd: 0.16.7

**Comment by alexellis** [comment]
Hi, it sounds like you are running into a timeout issue.

You can find out how to configure timeouts in the eBook, make sure you have the latest copy from Gumroad.

Alex

**Comment by alexellis** [comment]
Since I know this is working and have documented it, we'll get this closed. So if you need additional help or support please join the community call: https://docs.openfaas.com/community/
