### ISSUE TITLE
Faasd should support scale one replica to zero when there is no traffic.

### ISSUE THREAD

**Issue by shivabohemian** [openfaas/faasd#310]
## Why do you need this?
It's necessary to scale to zero when there's no traffic in a cost sensitive project!

## Who is this for?

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?

## Expected Behaviour

For example, when I deploy with label "com.openfaas.scale.zero=true, com.openfaas.scale.zero-duration=1m", it should scale to zero.

## Current Behaviour

Always one replica.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Your Environment
* OS and architecture:

* Versions:

```sh
go version
go version go1.19.3 linux/arm64

containerd -version
containerd github.com/containerd/containerd v1.6.8

uname -a
Linux 4.19.232  aarch64 GNU/Linux

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

faasd version
0.15.0-rc3
```

**Comment by alexellis** [comment]
/set title: Is Scale to Zero included in faasd?
