### ISSUE TITLE
Queue Worker stops to work

### ISSUE THREAD

**Issue by christiansicari** [openfaas/faasd#312]
I am massively using the asynchronous features provided in OpenFaas in a Multipass VM in a Ubuntu host.
I am currently running this version of faasd: 0.16.7	commit: 282b05802cccd311678a73efaee78af0086cc7fd

I do not have many logs to show. All of a sudden I stopped receiving the data at the provided callback URL.
What I see is that the queue-worker container is stopped, if I restart the machine or the container it comes up again, but in the journalctl it doesn't log anything.
![image](https://user-images.githubusercontent.com/29756552/208523548-c02adc36-6cb7-411c-9214-f55c5eac7801.png)

If I invoke any async function I get 202 results, but I don't see anything new in the logs
![image](https://user-images.githubusercontent.com/29756552/208524403-46618302-28db-4f38-b51a-099cdc71eaa1.png)

What I can do is reinstall faasd

**Comment by alexellis** [comment]
Hi @christiansicari you could restart faasd with the instructions in the eBook?

In future, please can you use the issue template. We do need everyone to fill that out instead of deleting it :smile: 

Good luck.

Alex
