### ISSUE TITLE
Remove basic auth plugin

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#314]
Remove basic auth plugin

## Why do you need this?

In 0.26.0 of the gateway, we removed the basic auth plugin by building it directly into the gateway itself.

## Who is this for?

All faasd users.

## Current Behaviour

Uses the auth plugin

## Expected Behaviour

In the docker-compose.yaml file remove env-vars that set up the auth plugin for the gateway, then remove the auth plugin from the file.

Then, go through a basic test with deploying a function, checking the API still requires auth with curl and still allows auth to work for the protected endpoints like /system/functions.

**Comment by alexellis** [comment]
@nitishkumar71 could you take a look please?

**Comment by nitishkumar71** [comment]
Sure

**Comment by alexellis** [comment]
Thanks @nitishkumar71
