### ISSUE TITLE
faas-cli login " Must provide a non-empty password via --password or --password-stdin"

### ISSUE THREAD

**Issue by lambda7xx** [openfaas/faasd#324]
## My actions before raising this issue
I use the [./hack/install.sh](https://github.com/openfaas/faasd) to deploy the faasd on my machine

Then I run the [faas-cli deploy -f ./hello-python.yml](https://docs.openfaas.com/tutorials/first-python-function/) to deploy a example. 

Then I meet this issue 
![image](https://user-images.githubusercontent.com/35867865/227698664-9157cfe6-04b5-4b96-9d48-23260b3eea5f.png)

## Why do you need this?
I use the openfaas as my research baseline 

## Who is this for?

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* OS and architecture:

* Versions:

```sh
go version

containerd -version: containerd containerd.io 1.6.19 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f

uname -a:  Linux ip-172-31-34-4 5.4.0-1094-aws #102~18.04.1-Ubuntu SMP Tue Jan 10 21:07:03 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release:  VERSION="18.04.6 LTS (Bionic Beaver)"

faasd version: faasd version: 0.16.9   commit: e1d90bba609a55ca123d26e5b7e1ccfcfedf3e8f
```

**Comment by alexellis** [comment]
Hi @lambda7xx are there any contents in that file you're running into faas-cli login?

There's no known issues here, and I ran this workflow only a couple of days ago.

If faasd is new to you, I'd suggest you get a copy of [the eBook](https://store.openfaas.com/l/serverless-for-everyone-else), it's the manual for faasd and contains all the proper login commands etc.

I'm going to close this now as cannot reproduce. If you still have issues after buying the eBook and following the manual, come back and comment here again.

Alex
