### ISSUE TITLE
Serverless Function Question

### ISSUE THREAD

**Issue by HKBazzi** [openfaas/faasd#335]
## My actions before raising this issue
Before you ask for help or support, make sure that you've [consulted the manual for faasd](https://openfaas.gumroad.com/l/serverless-for-everyone-else). We can't answer questions that are already covered by the manual.

## Why do you need this?
My team and I are testing out serverless functions in ADAS applications. We have a raspberry Pi and a lidar detector that warns a user if an object comes within 2meters of distance. We have a MQTT Broker, that sends a message to the MQTT Connector, that then invokes our serverless function on open-faas to display to the user that an object has been detected. We want to include a way to stop our RC Car we have everything mounted onto from our serverless function. We currently have it running on a local function that is deployed on the raspberry pi. Is there a way we can have it so our Open-Faas function can communicate with our RC Car? 

## Who is this for?
This is for our University Senior Capstone Research Project

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?
University of Michigan

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* OS and architecture:

* Versions:

```sh
go version

containerd -version

uname -a

cat /etc/os-release

faasd version
```

**Comment by nitishkumar71** [comment]
You can use MQTT to publish message back to RC Car. As your RC Car may be publishing message to MQTT topic. It can also subscribe to another topic to listen messages received. You can publish that from function.

**Comment by alexellis** [comment]
Thanks for the question, closing as answered by @nitishkumar71

**Comment by alexellis** [comment]
MQTT details: https://docs.openfaas.com/reference/triggers/#mqtt-connector
