### ISSUE TITLE
Multi-node support

### ISSUE THREAD

**Issue by LanYuqiao** [openfaas/faasd#339]
Although doc says that multi-node support will not be considered on faasd, I still want some suggestion for enabling faas-provider with muilti-node scaling ability (I mean without the dependence of K8S or other container orchestration tools, let faas-provider itself have the ability to scale the functions to other nodes). Actually I'm working on it as my master degree work, but I don't know how to get it started, anyone can give me some suggestions?

**Comment by alexellis** [comment]
Hi @LanYuqiao for clustering is a non-goal for faasd as you'll see in the [roadmap](https://github.com/openfaas/faasd/blob/master/docs/ROADMAP.md).

You should use Kubernetes with K3s to scale out.

faasd is a single node appliance, and self-contained.

K3s is really quite simple to use, you should take my free course on it - https://training.linuxfoundation.org/training/introduction-to-kubernetes-on-edge-with-k3s-lfs156x/

Alex

**Comment by LanYuqiao** [comment]
Thanks for your reply. I understand that Clustering for faasd is a non-goal and I had read the roadmap. And I also know that K8S or K3S or other container orchestration platforms can be used to scale out the faas function.

What I want to do is integrating the scale out ability into the faas provider itself. Is that possible or meaningful? Or is there any implementation of faas provider that has already achieved this?

> Hi @LanYuqiao,
> 
> Clustering for faasd is a non-goal as you'll see in the [roadmap](https://github.com/openfaas/faasd/blob/master/docs/ROADMAP.md).
> 
> You should use Kubernetes with K3s to scale out.
> 
> faasd is a single node appliance, and self-contained.
> 
> K3s is really quite simple to use, you should take my free course on it - https://training.linuxfoundation.org/training/introduction-to-kubernetes-on-edge-with-k3s-lfs156x/
> 
> Alex

**Comment by alexellis** [comment]
That's exactly the same thing. K3s/K8s has solved this problem completely and entirely. Any time spent here would be wasted, and a worse solution than what's already available and run in production [by many different companies](https://github.com/openfaas/faas/blob/master/ADOPTERS.md).

You can read prior notes and conclusion by clicking on the link in the roadmap, but we won't consider any contribution or further discussion.

https://github.com/openfaas/faasd/issues/225
