### ISSUE TITLE
Developer onboarding

### ISSUE THREAD

**Issue by gabeduke** [openfaas/faasd#34]
As a new developer I would like to stand up an environment in a limited number of steps to start iterating on new code.

## Proposal

Below is a first pass at standing up a VM in multipass with some helper scripts for syncing the project and redeploying from source. 

https://github.com/alexellis/faasd/compare/master...gabeduke:master

Steps to validate (check out my fork):

1. `make multipass-run` (type yes when the prompt shows up to add pub key)
1. `make ssh` will rsync the repository to the appropriate place inside the multipass VM's GOPATH then ssh into the directory
1. `make dev` will rsync the repository into the multipass VM, build the go package and switch the new binary out with the running systemd service

## Your Environment

* OS and architecture:
tested on Ubuntu 19.10 x86_64

**Comment by alexellis** [comment]
Since the PR is closed I'll close the issue too. @gabeduke thanks for helping out.

**Comment by gabeduke** [comment]
No prob 👍
