### ISSUE TITLE
Terrraform install fails on macOS Sonoma

### ISSUE THREAD

**Issue by opn** [openfaas/faasd#349]
## My actions before raising this issue
Followed instructions here - https://www.openfaas.com/blog/faasd-tls-terraform/

## Why do you need this?
Installing FaasD on DO

## Who is this for?
Feedback for you to update installation instructions.

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?
Astral Ship - community in Wales

## Expected Behaviour
`terraform init` would complete without complaint

## Current Behaviour

```sh
Initializing provider plugins...
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/template from the dependency lock file
- Reusing previous version of digitalocean/digitalocean from the dependency lock file
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
- Installing digitalocean/digitalocean v2.11.0...
- Installed digitalocean/digitalocean v2.11.0 (signed by a HashiCorp partner, key ID F82037E524B9C0E8)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.

```

## List All Possible Solutions and Workarounds
No idea

## Which Solution Do You Recommend?
None

## Steps to Reproduce (for bugs)
As per blog post - 

## Your Environment

* OS and architecture: MacOS Sonoma M2 silicon

* Versions:
Sonoma 14.0 (23A344)
Apple M2
Terraform v1.6.3

**Comment by opn** [comment]
Succeeded in installation on a Windows Machine, running Linux. Issue is a Terraform issue based on lack of support for latest macOS / hardware / software. Will update here if we ever manage to install on M2 machine.

**Comment by alexellis** [comment]
Hi @opn this sounds like an issue upstream with Terraform/DigitalOcean's support for Arm Macs.

I'm not sure if you've heard of Rosetta, but it can be used to get around lack of support in the ecosystem.

https://apple.stackexchange.com/questions/436773/how-can-i-run-a-script-in-rosetta-from-terminal-on-m1-mac

If you wanted to look into this and perhaps update the various modules, you may find they now support it?

I'll get this closed as resolved, but if you want to put the time in, we'd be open to a PR.
