### ISSUE TITLE
support faasd get 

### ISSUE THREAD

**Issue by nitishkumar71** [openfaas/faasd#360]
## Due diligence
Support `faasd` get for `arkade get faasd`
https://github.com/openfaas/faasd

## My actions before raising this issue
Before you ask for help or support, make sure that you've [consulted the manual for faasd](https://openfaas.gumroad.com/l/serverless-for-everyone-else). We can't answer questions that are already covered by the manual.

**Comment by alexellis** [comment]
Thank you :+1:
