### ISSUE TITLE
MemoryLimit needs changing to: MemoryMax

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#363]
## Description

MemoryLimit needs changing to: MemoryMax as per this warning:

```
May 17 13:21:43 welcome-mole systemd[1]: /usr/lib/systemd/system/faasd.service:6: Unit uses MemoryLimit=; please use MemoryMax= instead. Support for MemoryLimit= will be removed soon.
```

See also: https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html#MemoryMax=bytes

There is another unit for faasd-provider too.

**Comment by withhaotian** [comment]
Same problem.
