### ISSUE TITLE
What is the difference     ？？faas 

### ISSUE THREAD

**Issue by icetech233** [openfaas/faasd#369]
faas

**Comment by alexellis** [comment]
Hi @icetech233 your question is unclear. Can you take a few moment to write a sentence or two about what you wish to learn?

If we don't hear from you shortly, we will close the issue as potential spam.

**Comment by alexellis** [comment]
I've seen a pattern of similar low-quality issues raised on various OSS projects.

I'm going to point you and future visitors to https://docs.openfaas.com/deployment/ and then get this closed.
