### ISSUE TITLE
Add labels to OpenFaas functions from the function spec

### ISSUE THREAD

**Issue by utsavanand2** [openfaas/faasd#40]
Add labels to OpenFaas functions from the function spec

## Expected Behaviour

We should be able to add a label to a function by adding it to container definition.

So, when we run:
`faas-cli store deploy figlet --label hello=world`

We should get back the labels with:
`faas-cli describe figlet`

## Current Behaviour

Labels are not added

## Possible Solution

A PR is in the works

## Steps to Reproduce (for bugs)

1>`faas-cli store deploy figlet --label hello=world`
2> `faas-cli describe figlet` # Won't print out labels

This feature works perfectly with faas-netes (OpenFaas running on Kubernetes), but we need to port this functionality here too.

This issue is a duplicate of this [issue](https://github.com/alexellis/faas-containerd/issues/19) by @alexellis  on the archived [faas-containerd](https://github.com/alexellis/faas-containerd) repo

**Comment by martindekov** [comment]
I can take a look at this 👍

**Comment by martindekov** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Thank you 💪

**Comment by carlosedp** [comment]
Hey @martindekov, I've added some references on the previous issue:

Doc: https://godoc.org/github.com/containerd/containerd#WithContainerLabels

Code:

https://github.com/openfaas/faasd/blob/4775a9a77ce260857a2ef34326bd9c768b193db5/pkg/provider/handlers/deploy.go#L100.

**Comment by martindekov** [comment]
Thanks for pointing the right place @carlosedp 👍 Definitely saved me time searching it 🍻
