### ISSUE TITLE
add Dockerfile

### ISSUE THREAD

**Issue by AkihiroSuda** [openfaas/faasd#42]
## Expected Behaviour

faasd should be locally testable using Docker

## Current Behaviour

multipass is required

## Possible Solution

Install faasd and containerd in a single container together, along with systemd.

**Comment by GavinRay97** [comment]
Containerizing `faasd` with Docker would mean you would be able to deploy it to Serverless Container platforms like Cloud Run and Fargate, right?

**Comment by AkihiroSuda** [comment]
Yes if they support `--privileged` otherwise no.

The main purpose is ease of getting started and testing.
