### ISSUE TITLE
Improve response when requesting logs

### ISSUE THREAD

**Issue by martindekov** [openfaas/faasd#46]
In Slack customer complained about the response of the missing implementation of the log handler it returned:
```
pi@raspberrypi:~ $ faas-cli logs nslookup --follow --tls-no-verify
Server returned unexpected status code: 500 - log request failed
pi@raspberrypi:~ $ journalctl -u faasd
Feb 16 14:48:59 raspberrypi faasd[325]: [faasd] proxy: http://10.62.0.10:8080/system/logs?follow=true&name=nslookup&tail=-1
Feb 16 14:48:59 raspberrypi faasd[325]: 2020/02/16 13:48:59 Validated request 200.
Feb 16 14:48:59 raspberrypi faasd[325]: 2020/02/16 13:48:59 LogProxy: forwarding request failed: EOF
```

## Expected Behaviour

Return more verbose response, by implementing the LogsHandler from the faas-provider similar to how we do it with namespaces:
https://github.com/openfaas/faasd/blob/4bca5c36a55dcdaa4b0debf4989def205c0735d1/cmd/provider.go#L82
https://github.com/openfaas/faasd/blob/4bca5c36a55dcdaa4b0debf4989def205c0735d1/cmd/provider.go#L92

## Current Behaviour

Log handler is not implemented and returns: `log request failed` with status code `500`

## Possible Solution

As explained in Expected Behaviour section. Implement logs handler to return more verbose output for example:
```
The LogsHandler is not yet implemented.
```

## Steps to Reproduce (for bugs)

1. Deploy faasd
2. Deploy figlet on it
3. Invoke figlet couple of times
3. Run `faas-cli logs figlet --follow --tls-no-verify`
4. Check the not very explanatory response: `Server returned unexpected status code: 500 - log request failed` from the CLI here: 
https://github.com/openfaas/faas-cli/blob/30b7cec9634c708679cf5b4d2884cf597b431401/proxy/logs.go#L66
## Context

As per the general summary.

## Your Environment

* OS and architecture:
N/A
* Versions:
N/A
```sh
go version
N/A
containerd -version
N/A
uname -a
N/A
cat /etc/os-release
N/A
```

**Comment by alexellis** [comment]
Closed by https://github.com/openfaas/faasd/commit/dc8667d36a7b9588ecb0668d88163ada23be2b75
