### ISSUE TITLE
[Feature] Add support for logs via API

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#47]
## Feature

This feature would add support for retrieving logs via the REST API.

Today users can ssh into a faasd machine and run `journalctl -u faasd`, however, if faasd restarts, the containers become disconnected from the parent process and they no-longer stream output via journalctl.

I don't know how to store / disconnect logs from containerd, but Kubernetes and [the CRI interface](https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/) [may show](https://github.com/containerd/cri) some potential ways of doing this.

There is also a "shim" example from the containerd team, but this is not a fully worked solution. The idea is that a "shim" executable is responsible for starting the container instead of "faasd" itself. The shim executable survives restarts of faasd and can redirect logs to a known location.

An idea may be for us to store logs via syslog or journalctl and then have the API "get/read" logs back from there.

We may need to combine both approaches.

**Comment by alexellis** [comment]
From @estesp (containerd maintainer):

> ...this might help.. you could even track this back to a higher level as there is a CRI command to get logs (e.g. crictl logs ..) that I assume ends up being implemented by this feature of attaching writers to the containerd container IO impl. https://github.com/containerd/cri/blob/c23ed3befc08b3b85ea3fb50c6c99330871e9295/pkg/server/io/container_io.go#L204

> There is also a logger impl in that same package that is how the CRI plugin actually writes out to log files, which could be done in your client as well: https://github.com/containerd/cri/blob/c23ed3befc08b3b85ea3fb50c6c99330871e9295/pkg/server/io/logger.go

**Comment by alexellis** [comment]
CRI appears to store logs on disk: https://www.youtube.com/watch?v=cudJotS97zE

![Screenshot 2020-02-23 at 07 49 29](https://user-images.githubusercontent.com/6358735/75105947-2bf30100-5611-11ea-9bb0-85b43e178bd3.png)

**Comment by alexellis** [comment]
`crictl logs` -> https://github.com/kubernetes-sigs/cri-tools/blob/86dfb0fd89eeda5e34ee3cb89ded812dc74d5ff0/vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs/logs.go#L272

**Comment by alexellis** [comment]
Here's an example of using the CRI logging code to write to a file, from a ping process started outside of a container. It should be possible to hook it up to the container from containerd.

https://gist.github.com/alexellis/f232fe1fd2fe5278d411732af2645d79

The issue I see is that if faasd restarts, we'll lose the logs of the process since the io/copy is done in the parent.

At a guess (I may be wrong) - we need to fork a separate long-running process after starting the container to copy the log streams, or have that process start the container. This feels like a lot of indirection and "janky". I would like to get more input from those in the know.

**Comment by alexellis** [comment]
K8s logging architecture - https://kubernetes.io/docs/concepts/cluster-administration/logging/#logging-at-the-node-level "Everything a containerized application writes to stdout and stderr is handled and redirected somewhere by a container engine" 🤔

**Comment by alexellis** [comment]
Further example (albeit an old one) from @crosbymichael  - https://github.com/containerd/containerd/pull/3085

**Comment by nanikjava** [comment]
If you kill faasd from command using 

`sudo ps aux | grep -i faas    | awk '{print $2}' | sudo xargs kill -9 
`

you will see the containers are still running using the command

`sudo ./ctr tasks ls
`

following is what I see on my machine (Linux Ubuntu 19.04)

```
TASK                 PID     STATUS    
gateway              3032    RUNNING
queue-worker         3222    RUNNING
basic-auth-plugin    2620    RUNNING
nats                 2728    STOPPED
prometheus           2850    RUNNING

```
only the nats container is stopped while the rest is running.

Using the command

`sudo ./ctr tasks attach gateway
`

able to attach to the container 'gateway' and the log is streamed.

Is this the behaviour you looking for ?

**Comment by alexellis** [comment]
We have logs now via #50 - they are recorded via the systemd journal, but not queried back via the API.

This package may be of help/use:

https://github.com/coreos/go-systemd/blob/a4887aeaa186e68961d2d6af7d5fbac6bd6fa79b/sdjournal/read.go#L67

**Comment by alexellis** [comment]
This issue is about implementing the logs handler for log retrieval (pending) and also for log recording (that part is completed now) cc @LucasRoesler as mentioned on Slack https://openfaas.slack.com/archives/C1D32GFS8/p1582487994062300

**Comment by alexellis** [comment]
I would like to avoid any dependency on CGO as this will create issues when deploying to different OSes. sdjournal seems to take a hard dependency on it.

**Comment by alexellis** [comment]
Orbit by @ehazlett execs `journalctl`, that may be the reason why.

https://github.com/stellarproject/orbit/blob/45483b663600e92c8de516a127c0ed13ec5268be/cmd/ob/log.go

**Comment by LucasRoesler** [comment]
Does that mean that exec is ok then?

**Comment by alexellis** [comment]
We used exec here, thank you @LucasRoesler for your work on the feature. Closing the issue.
