### ISSUE TITLE
Migrate to Go modules and remove vendor dir

### ISSUE THREAD

**Issue by carlosedp** [openfaas/faasd#63]
## Expected Behaviour

Use Go modules instead of `dep` and remove `vendor` directory since go modules now handles caching into `~/go/pkg/mod`.

The advantage is that it's built-in Go since 1.13 and production on 1.14 ready as stated in https://blog.golang.org/go1.14.

## Current Behaviour

Building requires `dep`, an external application.

## Possible Solution

Will submit a PR if the proposal gets +1.

**Comment by alexellis** [comment]
Not approved. Please hold off on this.

**Comment by alexellis** [comment]
We've gone over to Go modules, but the vendor directory should say.
