### ISSUE TITLE
Logs showing -- no entries--

### ISSUE THREAD

**Issue by mphuie** [openfaas/faasd#68]
I have a simple python3 function deployed that adds a print statement in the handler, nothing else in the template is changed.  I've invoked it several times.

When SSH to the host and run `journalctl -t openfaas-fn:<function name>`, I get 
no log entries.  The end timestamp shown does reflect the last invocation time, but no logs are displayed

`journalctl -t openfaas-fn:testsql
-- Logs begin at Sun 2020-04-12 23:21:43 EDT, end at Mon 2020-04-13 01:18:31 EDT. -
-- No entries --`

## Your Environment

Ubuntu 118.04.4

* Versions:

```sh
go version

go not installed

containerd -version

containerd github.com/containerd/containerd v1.3.2 ff48f57fc83a8c44cf4ad5d672424a98ba37ded6

uname -a

Linux vps262182 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
```

**Comment by alexellis** [comment]
We will need a code sample to reproduce the error. Could you set up a repo please?
