### ISSUE TITLE
Timeout of long function execution

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#69]
I hit a timeout of a long function execution

The issue can be reproduced with this: https://github.com/alexellis/go-long

I checked the gateway, it's hard-coded to 60s

The provider has a read/write timeout set of the same value

However, @LucasRoesler suggested that there is also an upstream timeout value that also needs a value and is defaulting to 8-10s.

https://github.com/openfaas/faasd/blob/70e7e0d25a4ed97f7c227713466397a5e06643a1/pkg/provider/config/read.go#L15

```
pi@faasd-pi:~ $ sudo journalctl -f -t faasd
-- Logs begin at Sun 2020-03-08 18:58:18 GMT. --
Apr 16 16:54:27 faasd-pi faasd[16336]: [faasd] proxy: http://10.62.0.210:8080/async-function/make-ca
Apr 16 16:54:39 faasd-pi faasd[16336]: [faasd] proxy: http://10.62.0.210:8080/async-function/make-ca
Apr 16 16:54:40 faasd-pi faasd[16336]: [faasd] proxy: http://10.62.0.210:8080/async-function/make-ca
Apr 16 16:55:24 faasd-pi faasd[16336]: 2020/04/16 15:55:24 Get http://faasd-provider:8081/system/functions: dial tcp: i/o timeout
Apr 16 16:58:54 faasd-pi faasd[16336]: 2020/04/16 15:58:54 Get http://faasd-provider:8081/system/functions: dial tcp: i/o timeout
Apr 16 17:15:59 faasd-pi faasd[16336]: [faasd] proxy: http://10.62.0.210:8080/
Apr 16 17:15:59 faasd-pi faasd[16336]: [faasd] proxy: http://10.62.0.210:8080/ui/
Apr 16 17:15:59 faasd-pi faasd[16336]: 2020/04/16 16:15:59 Validated request 401.
Apr 16 17:15:59 faasd-pi faasd[16336]: [faasd] proxy: http://10.62.0.210:8080/ui/
Apr 16 17:15:59 faasd-pi faasd[16336]: 2020/04/16 16:15:59 Validated request 401.
```

**Comment by alexellis** [comment]
This might be a red herring since I may have been invoking without a POST method. Closing for the time being. We should look at changing the timeout to being dynamic though.

**Comment by tmiklas** [comment]
Reproduced accidentally...

Turned out that whatever I set timeout was hard set for 10sec.  Changing read/write timeout alone did not help (as per [OpenFaaS Troubleshooting](https://docs.openfaas.com/deployment/troubleshooting/)) but adding the following to `stack.yml`, shamelessly taken from [go-long example](https://github.com/alexellis/go-long/blob/master/stack.yml) solved it :-)

```
    environment:
      write_timeout: 3m
      read_timeout: 3m
      exec_timeout: 3m
      handler_wait_duration: 60s
```

**Comment by alexellis** [comment]
This issue doesn't apply anymore given the configuration with the compose file.

The timeouts need to "agree" between the function and the core services, there is a new tutorial for this: https://docs.openfaas.com/tutorials/expanded-timeouts/

**Comment by dsrowell** [comment]
I wanted to leave this in case someone else gets here attempting to use long function execution specifically with **faasd** (which I love). In addition to adding the *_timeout values to the /var/lib/faasd/docker-compose.yaml and the function's yaml file, I had to create the following file:

```/etc/systemd/system/faasd-provider.service.d/override.conf```

with the following contents:

```
[Service]
Environment="service_timeout=5m"
```
to bump the gateway's timeout to 5 minutes. I am happy to hear if there is a better/easier way (I only tested on ubuntu 20.04), but if not, I hope this helps others.

**Comment by ikhyunAn** [comment]
I've modified the var/lib/faasd/docker-compose.yaml and also added docker-compose.yaml to my function's root folder. However the timeout is still hard-fixed and unable to see any change. I would really appreciate it if someone can provide a step-by-step guide to modify the timeout!

**Comment by alexellis** [comment]
Hey @ikhyunAn this is all covered in the eBook. I'd suggest you buy a copy.

https://store.openfaas.com/l/serverless-for-everyone-else

Alex
