### ISSUE TITLE
Update the Docker images for the core components

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#73]
We need to update the tags for the Docker images used for the OpenFaaS core components such as the gateway and queue-worker.

Whoever makes this change should also look at what environment variables and configuration items have been introduced and fine-tune accordingly. For instance the queue-worker should now have `max_inflight` set to something like `5` to enable concurrency.

## Acceptance

Testing will need to be performed to show that faasd works as expected after the upgrade. The logs from faasd and faasd-provider will show the version numbers of the components. Please give before/after output.

**Comment by Hsiny** [comment]
Hi, Alex , I want to know if we need to do these things for this issue

1. Save the log before upgrade
2. Upgrade the docker image verison in [up.go](https://github.com/openfaas/faasd/blob/master/cmd/up.go) , and update configuration items whitch have been introduced and fine-tune accordingly  
3. Retest and make sure the faasd works as expected, save the log after upgrade

**Comment by alexellis** [comment]
That sounds fine to me, would you like to take this issue @Hsiny ?

**Comment by Hsiny** [comment]
ok, I will do these work I listed and then create a PR

**Comment by alexellis** [comment]
Please bear in mind that there is a PR template to use, which has fields we would like to see filled in.

One other requirement is that for each commit you use `git commit -s` instead of just `git commit`. This adds your Signed-off-by line as described in the contributing guide. 

Thanks

**Comment by Hsiny** [comment]
@alexellis 
Hi, Alex, I have created a PR about this Issue https://github.com/openfaas/faasd/pull/74

**Comment by alexellis** [comment]
Thank you @Hsiny, I've merged that change but there is one piece that you may have missed.

> Whoever makes this change should also look at what environment variables and configuration items have been introduced and fine-tune accordingly. For instance the queue-worker should now have max_inflight set to something like 5 to enable concurrency.

Could you cover this part?

> The queue-worker should now have max_inflight set to something like 5 to enable concurrency.

**Comment by Hsiny** [comment]
Hi, Alex, the `max_inflight` is alearde set to 1, and I check this config in other project(faas-nets,aas-swarm), the default value is 1 also.

**Comment by Hsiny** [comment]
Hi , Alex , the `max_flight` for queue-worker  is already set to `1`, and I check this configuration item  in other projects(faas-swarm,faas-netes), the default value is `1`also.  
Do I need to fine-tune this value? or just set the default value to 1 and let the user set it?

**Comment by alexellis** [comment]
I think we should set it to 5 for faasd since it can't be changed without rebuilding

**Comment by Hsiny** [comment]
I'm sorry, I should have discussed it with you in advance.   
Do I need to change it in another PR？

**Comment by alexellis** [comment]
Don't worry. Yes new PR please. I've merged your previous one.

**Comment by Hsiny** [comment]
OK, PR is created, https://github.com/openfaas/faasd/pull/75

**Comment by Hsiny** [comment]
Thank you very much. If there is anything else like this, please contact me. I would like to make some open source contributions
