### ISSUE TITLE
Cannot push to Docker Hub

### ISSUE THREAD

**Issue by nicoschi** [openfaas/faasd#88]
Hi there, I'm testing faasd on a local Centos 7 virtualbox VM but I'm stucking on pushing the image after the build. 

## Expected Behaviour
Image push on Docker Hub and function build

## Current Behaviour
Stacking on push to Docker Hub with the following error: 
`error: failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed`

## Steps to Reproduce (for bugs)
1. Install faasd and moby/buildkit (OK)
2. faas-cli login (OK)
3. create a folder with a new function  (OK): 

```bash
mkdir myfunc
cd myfunc
faas-cli new myfunc --lang python3
```

4. edit myfunc.yml image to `nicoschi/myfunc:latest`  (OK)
5. build the function with: `faas-cli build -f myfunc.yml --shrinkwrap`  (OK)
6. create a `~/.docker/config.json` with the auth value equal to `echo $(echo -n "DOCKERUB_USERNAME:DOCKERUB_PASSWORD" | base64)` (OK):  

```json
{
 "auths": {
  "https://index.docker.io/v1/": {
   "auth": "myauth"
  }
 }
}
```

7. start buildkit with: `sudo /usr/local/bin/buildkitd &`  (OK)
8. build the function  (KO with `error: failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed`): 

```bash
sudo -E /usr/local/bin/buildctl build --frontend dockerfile.v0  \
  --local context=build/myfunc/
  --local dockerfile=build/myfunc/
  --output type=image,name=docker.io/nicoschi/myfunc:latest,push=true
```

## Context
I installed faasd manually using steps in the [cloud-config.txt file](https://raw.githubusercontent.com/openfaas/faasd/master/cloud-config.txt) and buildx starting from [this article](https://blog.alexellis.io/building-containers-without-docker/#buildwithbuildkitstandalone) but as of now I can deploy a new function in the ui from store but i can't deploy and test a custom one created through the faas cli. 

## Environment

* OS and architecture: Linux 3.10.0-1127.el7.x86_64 / CentOS Linux release 7.8.2003 (Core)

* Versions:

```sh
go version
go version go1.13 linux/amd64

containerd -version
containerd github.com/containerd/containerd v1.3.2 ff48f57fc83a8c44cf4ad5d672424a98ba37ded6

uname -a
Linux new-host-3 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7" 
```

Thanks

**Comment by alexellis** [comment]
Despite you following a third-party blog post on using buildkit with faasd, this isn't an issue with faasd so we're going to need to close it out.

You can ask for help on OpenFaaS Slack though. Mehdi is also there, so you can ask him about his tutorial.

**Comment by alexellis** [comment]
https://slack.openfaas.io

**Comment by nicoschi** [comment]
The blog post wasn't from Mehdi but from you, maybe you read the first version of the issue: 

https://blog.alexellis.io/building-containers-without-docker/#buildwithbuildkitstandalone
