### ISSUE TITLE
Customise hostname in terraform scripts

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#95]
## Expected Behaviour

I want to customise the hostname in the terraform scripts

## Current Behaviour

it's always `faasd`  + $DOMAIN

## Possible Solution

Extend the scripts - maybe @mehyedes or @Waterdrips would like to take this?

**Comment by Waterdrips** [comment]
If any of our newer contributors wanted to have a go at this then:

This fixed `faasd` string needs changing to a variable, it can be defaulted to `faasd` to keep current functionality.

https://github.com/openfaas/faasd/blob/master/docs/bootstrap/digitalocean-terraform
/main.tf#L62

Then a test:
1) Test with not overriding the variable
2) Test with overriding the variable

Both test cases should pass and then this would be good to go

**Comment by Waterdrips** [comment]
/close 

done in #96
